mgechev/revive

fixtures/golint/unexported-return.go
test/golint_test.go

Improve tests

---

fixtures/golint/unexported-return.go
rule/unexported-return.go
test/golint_test.go

Fixes #5.
Please consider being a bit more patient before closing issues in the future.

Avoid false positives when returning interface values

---

fixtures/empty-lines.go
rule/empty-lines.go

Fix the same-line comments detection in the empty-lines rule

---

README.md
RULES_DESCRIPTIONS.md
config.go
fixtures/call-to-gc.go
rule/call-to-gc.go
test/call-to-gc_test.go

call-to-gc (new rule)

---

RULES_DESCRIPTIONS.md

Doc updated: fix typo

---

README.md

Fix the spelling of length in the README.
Closes #91

Fix spelling of length

---

README.md

Add excelize and aurora to "Who uses Revive"

---

RULES_DESCRIPTIONS.md

Adds missing `rule` in rules examples

---

README.md
RULES_DESCRIPTIONS.md
config.go
fixtures/bare-return.go
rule/bare-return.go
test/bare-return_test.go

New rule bare-return

---

README.md
RULES_DESCRIPTIONS.md
config.go
fixtures/unused-receiver.go
rule/unused-receiver.go
test/unused-receiver_test.go

new rule: unused-receiver

---

README.md
RULES_DESCRIPTIONS.md
config.go
fixtures/unhandled-error.go
rule/unhandled-error.go
test/unhandled-error_test.go

unhandled-error (new rule)

---

README.md

added line
- [`sklearn`](https://github.com/pa-m/sklearn) - A partial port of scikit-learn written in Go

proposal to add sklearn to "Who uses revive" in README

---

fixtures/struct-tag.go
rule/struct-tag.go

fix 208 struct-tag linter false positive

---

README.md

[Codeac.io](https://www.codeac.io?ref=revive) recently integrated revive and wants to help the open-source community around to grow. We hear positive feedback on this integration from our users so we would like to spread the word even more and help more developers deliver better code, faster. Feel free to try it yourself - we would appreciate any feedback from you guys as well.

Add Codeac.io - Automated code review tool

---

README.md

I was lucky to get early access to the GitHub Actions beta and started developing my own Action project yesterday. Since I use Revive in all my Go projects, I decided to develop a [Revive Action](https://github.com/morphy2k/revive-action).
It's not perfect yet, a few little things are missing, but it should work well in most projects out there :-)

Add Revive Action

---

fixtures/golint/exported.go
rule/exported.go

fixes issue #229

---

fixtures/bare-return.go
rule/bare-return.go

fixes issue #280

---

README.md
RULES_DESCRIPTIONS.md
config.go
fixtures/string-of-int.go
rule/string-of-int.go
test/string-of-int.go

String of int

---

fixtures/modifies-param.go
rule/modifies-param.go

fix issue #355

---

README.md
RULES_DESCRIPTIONS.md

update README and RULE_DESCRIPTIONS for #353

range-val-address: update readme and rule description

---

README.md
RULES_DESCRIPTIONS.md
config.go
rule/identical-branches.go
rule/utils.go
test/identical-branches_test.go
testdata/identical-branches.go

Identical branches

---

README.md
config.go
formatter/friendly.go
main.go

It forces colorizing for no TTY environments.
Tested:
TERM=dumb REVIVE_FORCE_COLOR=1 revive -formatter friendly ./...
Closes #418

feat(color): added support for the REVIVE_FORCE_COLOR=1 environment variable

---

README.md
RULES_DESCRIPTIONS.md
config.go
rule/unconditional-recursion.go
test/unconditional-recursion_test.go
testdata/unconditional-recursion.go

Unconditional recursion

---

README.md
RULES_DESCRIPTIONS.md
config.go
rule/defer.go
test/defer_test.go
testdata/defer-loop-disabled.go
testdata/defer-only-loop-enabled.go
testdata/defer.go

Defer rule

---

README.md
RULES_DESCRIPTIONS.md
config.go
rule/unexported-naming.go
test/unxeported-naming_test.go
testdata/unexported-naming.go

new rule: unexported-naming

---

rule/cognitive-complexity.go
testdata/cognitive-complexity.go

fixes issue #451

---

README.md
RULES_DESCRIPTIONS.md
config/config.go
rule/function-length.go
test/function-length_test.go
testdata/function-length1.go
testdata/function-length2.go
testdata/function-length3.go

new rule function-length

---

rule/range-val-address.go
rule/string-format.go
testdata/range-val-address.go

This will improve the range-val-address rule to detect more issues in the code.
Closes #513

range-val-address: improve detection

---

README.md
config/config.go
lint/config.go
rule/cyclomatic.go
rule/max-public-structs.go

Adds configuration option to enable all available rules

---

README.md

document how to configuring revive in golangci-lint

---

rule/add-constant.go
rule/call-to-gc.go
rule/deep-exit.go
rule/superfluous-else.go
rule/unconditional-recursion.go
rule/unreachable-code.go

simplify: redundant map composite literal

---

README.md

Fix a typo: "Rule tuning"

---

lint/file.go
test/disable-annotations_test.go
testdata/disable-annotations3.go

fix issue #540

---

README.md
RULES_DESCRIPTIONS.md
config/config.go
rule/useless-break.go
test/useless-break_test.go
testdata/useless-break.go

add new rule useless-break

---

rule/useless-break.go
testdata/useless-break.go

fix issue 556

---

README.md

updates installation instructions

---

RULES_DESCRIPTIONS.md

This PR is to update a broken link in the RULES_DESCRIPTIONS.md doc for cognitive-complexity.

Update moved cognitive-complexity whitepaper link

---

lint/file.go
rule/add-constant.go
rule/empty-block.go
rule/max-public-structs.go

fixed some complex code

---

rule/var-naming.go
test/var-naming_test.go
testdata/var-naming_test.go

fix #622 (Rule 'var-naming' should allow Fuzz_xxx)

---

rule/argument-limit.go

Fix a typo in an error message.

fix: invalid rule name in error message

---

.github/workflows/release.yml

I tested it here https://github.com/Clivern/abc & it should work

use ghcr.io

---

rule/range-val-in-closure.go
testdata/range-val-in-closure.go

fix issue #637

---

README.md

Adds documentation for the changes incorporated by #650

adds usage of revive as third party library

---

README.md

Fixed missing import in readme.

Fix README example's missing import

---

rule/nested-structs.go
testdata/nested-structs.go

fix issue 664

---

lint/package.go
rule/package-comments.go
testdata/golint/package-doc1.go

Make package comment more confident

---

README.md

doc: add devlake to README usage

---

rule/struct-tag.go
testdata/struct-tag.go

This PR adds support of protobuf struct tags to the rule ` struct-tag`

adds checks for protobuf struct tags

---

lint/package.go

[WIP] Move to the default importer from gcexportdata

---

rule/empty-lines.go
testdata/empty-lines.go

fix bug #739: empty-lines false positive

---

rule/function-length.go

fix bug #736: Data race in rule function-length

---

.goreleaser.yml

fixes Missing tag "latest" on container images uploaded to ghcr.io #786
Closes #786

Add tags to docker images built by GoReleaser

---

config/config.go
logging/logger.go
revivelib/core.go
test/golint_test.go
test/utils.go
testdata/unused-param.go

Move away from deprecated ioutils

---

rule/struct-tag.go
testdata/struct-tag.go

Fix prefix trimming in struct-tag

---

README.md

Proposing to add the Checker Go library to the list of Who Uses.

Adding Checker Go library to the list of Who Uses.

---

README.md

doc: add milvus to README usage (#845)

doc: add milvus to README usage (#845)

---

rule/import-shadowing.go
testdata/import-shadowing.go

fix: false positive in import-shadowing for method names

---

rule/dot-imports.go

fix: dot-imports now checks test files as well

---

RULES_DESCRIPTIONS.md

closes #901
only text modification so no steps to repoduce needed :)

cleanup rules descriptions

---

RULES_DESCRIPTIONS.md

docs: fix TOC item

---

RULES_DESCRIPTIONS.md

docs: typo in add-constant configuration

---

testdata/exported-issue-1045.go

related with #1045 
update testdata with case for disableChecksOnVariables

update testdata: var case

---

revivelib/core.go

related with #1056 
by default if we dont have any excludes, we can ignore vendor/...

feat: ignore vendor if no exclude set

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build.yaml
.github/workflows/lint.yaml
.github/workflows/release.yml
.github/workflows/test.yaml

Update version of the GitHub actions used by the CI.

chore: update actions

---

.github/workflows/release.yml

chore: fix typo

---

README.md

Add Indicator to the list of projects using Revive.
Closes #1064

Appending Indicator to the list of projects using Revive.

---

lint/linter.go
test/issue1100_test.go
testdata/goUnknown/go.mod
testdata/goUnknown/issue1100.go

fix: nil panic on old go.mod (issue #1100)

---

.github/workflows/test.yaml
cli/main_test.go

The PR adds `tests-on-windows` GitHub Actions workflow and fixes failing tests in the `cli` package.

fix: cli tests on Windows; add tests-on-windows workflow

---

rule/cognitive_complexity.go
testdata/cognitive_complexity.go

The PR extends `cognitive-complexity` rule with handling direct recursion.

cognitive-complexity: handle direct recursion

---

lint/linter.go

nit: add all wait group delta at once when linting over packages

refactor: add all wait group delta at once

---

rule/bool_literal_in_expr.go
rule/cognitive_complexity.go
rule/comment_spacings.go
rule/constant_logical_expr.go
rule/datarace.go
rule/identical_branches.go
rule/import_shadowing.go
rule/range_val_address.go
rule/redefines_builtin_id.go
rule/string_format.go
rule/unconditional_recursion.go
rule/unused_param.go
rule/unused_receiver.go
rule/utils.go
rule/waitgroup_by_value.go

This PR provides some clean up to make the code homogeneous and address minor issues:
* pointer vs. non-pointer struct receivers
* typos/grammar
* TODO comments on deprecations and potential bugs

chore: cleanup code in rules

---

README.md

docs: fix TOC in README

---

.github/workflows/test.yaml
cli/main_test.go

See https://github.com/mgechev/revive/pull/1237#issuecomment-2656101204

test: re-enable and fix test case for getVersion

---

RULES_DESCRIPTIONS.md

update description of struct-tag rule to take into account the recently added tags

doc: update description of struct-tag rule

---

rule/cognitive_complexity.go
testdata/cognitive_complexity.go

fix: cognitive complexity nesting with if-else chains

---

lint/file.go
rule/if_return.go
rule/struct_tag.go
rule/unhandled_error.go

Simplify code by running the command:
```
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
```
Read more about `modernize`: https://github.com/golang/tools/releases/tag/gopls%2Fv0.18.0

refactor: apply suggestions from gopls modernize

---

revivelib/core.go

this just fix a typo? so I didn't create an issue. 😂

fix: call fmt.Errorf with wrong err

---

internal/astutils/ast_utils.go
rule/get_return.go
testdata/get_return.go

Closes #1323 by detecting HTTP hander signature.

fix(1323): false positive in get-return rule for HTTP Get handlers

---

.github/workflows/lint.yaml
.markdownlint-cli2.yaml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
DEVELOPING.md
README.md
RULES_DESCRIPTIONS.md

This PR integrates [markdownlint](https://github.com/DavidAnson/markdownlint). I chose this tool because of the following reasons:
- The most widely-used Markdown linter.
- Highly configurable.
- Editor plugins available (VSCode, etc.).
Changes:
- Add [`markdownlint-cli2-action`](https://github.com/DavidAnson/markdownlint-cli2-action) CI/CD job.
- Create `markdownlint` config `.markdownlint-cli2.yaml`. Disable some rules.
- Fix found issues.
<details><summary>All found issues</summary>
<p>
```
Finding: *.{md,markdown} *.md
Found:
CODE_OF_CONDUCT.md
CONTRIBUTING.md
DEVELOPING.md
README.md
RULES_DESCRIPTIONS.md
Linting: 5 file(s)
Summary: 150 error(s)
CODE_OF_CONDUCT.md:5:151 MD013/line-length Line length [Expected: 150; Actual: 397]
CODE_OF_CONDUCT.md:27:151 MD013/line-length Line length …
```

chore: add linter for Markdown files

---

rule/unexported_return.go
testdata/golint/unexported_return.go

unexported-return: fix type aliases support

---

RULES_DESCRIPTIONS.md

Anchor at beginning/end as appropriate to avoid false positives, include ignorable string.Writer functions, avoid matching bytes.Buffer.WriteTo.

docs: improve unhandled-error ignore argument examples

---

.goreleaser.yml

This PR updates GoReleaser config:
- Improve comment
- Remove unnecessary hooks
- Include `docs` commits into changelog.

chore: clean up GoReleaser config, remove unnecessary hooks

---

.golangci.yml
.markdownlint-cli2.yaml
defaults.toml
revive.toml

This PR improves the clarity and completeness of configuration file comments.

chore: improve comments for config files

---

rule/enforce_switch_style.go
testdata/enforce_switch_style.go

fix(1438): enforce-switch-style - false positive with pure return switch

---

.github/workflows/test.yaml

Closes https://github.com/mgechev/revive/issues/1459.

chore: add macOS test runner

---

RULES_DESCRIPTIONS.md

docs: add missing use-waitgroup-go TOC entry

---

DEVELOPING.md

_Originally posted by @alexandear in https://github.com/mgechev/revive/pull/1491#discussion_r2303209047_

docs: add info about `golang` code snippets

---

RULES_DESCRIPTIONS.md

docs: enhance struct-tag rule description
