- README.md
- lint/linter.go
- lint/package.go
- rule/context-keys-type.go
- rule/errorf.go
- rule/time-naming.go
- rule/unexported-return.go
- rule/var-declarations.go
- untyped.toml
Enable optional type checking. This can improve the performance of the linter and make it >6x faster than golint.
> Introduce optional type checking

- formatter/stylish.go
- Changed from dark blue to cyan on "stylish" formatted errors, dark blue on black can be pretty hard to read if your office has windows or lights.
> Cyan for readability (better contrast)

- README.md
- fixtures/superfluous-else.go
- rule/superfluous-else.go
- test/superfluous-else_test.go
The new rule checks for `if-then-else` where the `then` block ends with branching statement like `continue`,`break`, or `goto`.
> Adds rule superfluous-else (an extension of indent-error-flow)

- .travis.yml
- Makefile
- fixtures/golint/exported.go
- rule/exported.go
The rule was failing in the following case:
```go
// A is an awesome type
type A = int
```
...because revive was skipping the leading `A`, considering it as an article.
@chavacava would you check this out?
> Fix rule for documentation of exported types

- README.md
- config.go
- formatter/json-stream.go
- formatter/ndjson.go
Adds newline delimited JSON stream. 
To be able to process the JSON data a little earlier ([example](https://github.com/morphy2k/linter-revive/blob/5596c5fe76ba178871c628ffb6472eefbe959f65/lib/main.js#L58))
> Add formatter NDJSON

- README.md
- config.go
- fixtures/add-constant.go
- rule/add-constant.go
- test/add-constant_test.go
Suggests creating constant for magic numbers and string literals
Rule configuration is of the form
```toml
[rule.add-constant]
arguments = [{maxLitCount = "2",allowStrs ="\"\"",allowInts="0,1",allowFloats="0.0,1.0"}]
```
(replaces previous PR)
> add-constant (new rule)

- README.md
- config.go
- fixtures/flag-param.go
- rule/flag-param.go
- test/flag-param_test.go
The rule `flag-parameter` warns on boolean parameters that create a [control coupling ](https://en.wikipedia.org/wiki/Coupling_(computer_programming)#Procedural_programming)
> flag-parameter (new rule)

- Gopkg.toml
- README.md
- config.go
- fixtures/struct-tag.go
- rule/struct-tag.go
- test/struct-tag_test.go
Checks common struct tags like `json`,`xml`,`yaml` and warns when using non-standard options or when expected types and values mismatch
> struct-tag (new rule)

- fixtures/struct-tag.go
- rule/struct-tag.go
The rule adds checks for `asn1` and `bson` tags
> struct-tag: add support for asn1 and bson

- README.md
- config.go
- fixtures/modifies-value-receiver.go
- rule/modifies-value-receiver.go
- test/modifies-value-receiver_test.go
This rule is the equivalent of `modifies-parameter` but applied to method receivers
Inspired by [Methods with Value Receivers Can't Change the Original Value](http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#method_val_receiver) of _50 Shades of Go: Traps, Gotchas, and Common Mistakes for New Golang Devs_
> modifies-value-receiver (new rule)

- README.md
- config.go
- fixtures/bool-literal-in-expr.go
- rule/bool-literal-in-expr.go
- rule/utils.go
- test/bool-literal-in-expr_test.go
Suggests removing boolean literals from logic expressions like `bar == true`, `arg == false`, `r != true`
It warns when logical expression always evaluates to the same value. For example it will detect that `false && boolExpr` and `boolExpr || true` always evaluate to `false` and `true` respectively.
> bool-literal-in-expr (new rule)

- README.md
Hi,
That's just a easy fix for confusing wrong naming of packages in errorf rule description.
> fix package names in docs for errorf rule

- rule/max-public-structs.go
The rule `max-public-structs` introduced a debug trace, this commit removes it.
> removes debug trace

- config.go
- formatter/unix.go
here an example:
```bash
$ revive -config revive.toml -formatter unix
main.go:24:9: [errorf] should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)
```
I think it's better than default because it clearly shows which rule is violated.
Furthermore it would facilitate result parsing by other tools which would enable better linter composition with revive, for example with the following regexp:
```
^(.+):(\d+):(\d+): \[(.+)\] (.+)$
```
> New formatter: unix

- config.go
A just faced with `cannot find rule: max-public-structs` when I tried to use this rule.
> Add missed max-public-structs rule to all list

- lint/package.go
> fix issue [#59]

- rule/atomic.go
- rule/constant-logical-expr.go
- rule/utils.go
> Refactors `atomic` rule code to move `gofmt` function to utils.go (issue #79) 

- config.go
- fixtures/empty-lines.go
- lint/file.go
- rule/empty-lines.go
- test/empty-lines_test.go
This is a rule that checks whether you have heading or trailing lines in your blocks.
```go
package fixtures
func f1(x *int) string { // MATCH /extra empty line at the start of a block/
return x > 2
}
func f2(x *int) string {
return x > 2 // MATCH /extra empty line at the end of a block/
}
func f3(x *int) string { // MATCH /extra empty line at the start of a block/
return x > 2 // MATCH /extra empty line at the end of a block/
}
func f4(x *int) string {
// This is fine.
return x > 2
}
func f5(x *int) string { // MATCH /extra empty line at the start of a block/
// This is _not_ fine.
return x > 2
}
func f6(x *int) string {
return x > 2
// This is fine.
}
func f7(x *int) string {
return x > 2 // MATCH /extra empty line at the end of a block/
// This is _not_ fine.
}
```
> Introduce the empty-lines rule that verifies there are no {head,trail}ing lines

- fixtures/empty-lines.go
- rule/empty-lines.go
There were many cases where the multi-line statements at the end of a
block were marked as containing empty lines, while they didn't. Or vice
versa.
You may check-out the tests. They have lots of new examples.
> Handle multi-line statements edge-cases in the multi-line rule

- RULES_DESCRIPTIONS.md
I did some formatting:
- There were new lines in the middle of a few sentences
- Added newlines before code blocks
- Removed trailing spaces
I also dropped statements in the form "This rule checks/does/warns...", when this was clear from the rule's explanation.
> docs: update the documentation

- README.md
Gitea is now using revive: https://github.com/go-gitea/gitea/commit/20c54f88b23bbf56ac3cc3a74baeed98d7ab0844
> docs: add gitea to "Who uses Revive"

- fixtures/line-length-limit.go
- lint/file.go
Closes #98
Warn: I've updated the test fixture for the `line-length-limit` rule but `revive`'s testing framework is not able to check failures on comments.
> fixes issue #98

- fixtures/disable-annotations2.go
- fixtures/line-length-limit.go
- lint/file.go
- test/disable-annotations_test.go
Closes #102 
Added test on disabling annotations with `next-line` and `line` modifiers. These tests cope with the error case identified by the issue #102
> Do not require additional newline for disabling multiple rules

- fixtures/golint/error-return.go
- rule/error-return.go
please check golint related updates here: golang/lint@8379672
When returning multiple values with an error,
lint checks if the error is the last return value.
But the implementation actually is checking for all return values
except for the last one, and throw the alert if it found an error.
There is a (edge) case where some function returning more than one error
is getting a false positive even when the last return value is an error.
This patch adds an early check, to see if the last return value is an error
and if so, it will pass silently.
> fix error return rule to allow multiple error return values

- rule/unused-param.go
- test/unused-param_test.go
This PR proposes a simpler and more memory/time efficient implementation of the `unused-parameter` rule.
The new implementation replaces the ad-hoc handling of ids scopes by leveraging `Obj` field of `ast.Ident` nodes.
Benchmark comparison of the current (old) and the proposed (new) implementation:
```
benchdiff old.txt new.txt
benchmark                  old ns/op     new ns/op     delta
BenchmarkUnusedParam-4     1126516       1044633       -7.27%
benchmark                  old allocs     new allocs     delta
BenchmarkUnusedParam-4     7086           6434           -9.20%
benchmark                  old bytes     new bytes     delta
BenchmarkUnusedParam-4     295103        264038        -10.53%
```
:warning: There is a minor change in the semantics of the rule. While the current …
> simpler and more efficient implementation of unused-parameter

- rule/imports-blacklist.go
- test/import-blacklist_test.go
Refactoring of `import-blacklist` to simplify code by removing unnecessary call to `ast.Walk` + other minor modifications.
Current vs new benchmarks:
```
$ benchdiff old.txt new.txt
benchmark                       old ns/op     new ns/op     delta
BenchmarkImportsBlacklist-4     114217        111158        -2.68%
benchmark                       old allocs     new allocs     delta
BenchmarkImportsBlacklist-4     455            448            -1.54%
benchmark                       old bytes     new bytes     delta
BenchmarkImportsBlacklist-4     38589         38265         -0.84%
```
> optimizes import-blacklist

- fixtures/struct-tag.go
- rule/struct-tag.go
Minor extension of `struct-tag` rule to warn when a private field has tags.
> Extend rule struct-tag to warn on private fields with tags

- .travis.yml
The docs cannot be built with latest now due to issues with Gatsby.
> Set specific node version

- formatter/stylish.go
Makes stylish formatter respect "Rule of Silence"
See http://www.linfo.org/rule_of_silence.html
Fixes #165
> fix: adhere to "Rule of Silence"

- go.mod
- go.sum
Fix #223 
Maybe something like this solve the issue because it is clear that there is a commit timestamp mismatch between https://github.com/mgechev/dots/commits/master and `revive` `go.mod` and `go.sum` and on new go version, there is a validation
```
// go.mod 
// this 
github.com/mgechev/dots v0.0.0-20190603122614-18fa4c4b71cc
// should be 
github.com/mgechev/dots v0.0.0-20181228164730-18fa4c4b71cc
```
```
// go.sum
// this
github.com/mgechev/dots v0.0.0-20190603122614-18fa4c4b71cc h1:ErGdrZWM/CrAz0FVwcznlAScsmr2pdSMMPMwFL9TNmw=  
github.com/mgechev/dots v0.0.0-20190603122614-18fa4c4b71cc/go.mod h1:KQ7+USdGKfpPjXk4Ga+5XxQM4Lm4e3gAogrreFAYpOg=
// should be
github.com/mgechev/dots v0.0.0-20181228164730-18fa4c4b71cc h1:SQHr6jXnsY5YmRoO7RWDcZjmC3PgwPW/xQ9TYJ/SiRY=
github.com/mgechev/dots …
```
> Fix mgechev/dots timestamp mismatch

- fixtures/golint/errorf.go
Go compiler would complain about using void-result
function value as a return expression.
> t.Error doesn't return a value

- fixtures/deep-exit.go
- fixtures/deep-exit_test.go
- rule/deep-exit.go
- test/deep-exit_test.go
Closes #290 and slightly simplifies the implementation of deep-exit rule
> fixes issue 290

- RULES_DESCRIPTIONS.md
- config.go
- fixtures/range-val-address.go
- rule/range-val-address.go
- test/range-val-address_test.go
See issue #352 for details
this rule will add the functionality to lint unwanted address assignments in range-loops.
i added a few test cases and these tests are passing. 
as i stated in issue #352, i have no experience with golang ast, so please review in detail.
Closes #352
> Add rule 'range-val-address'

- rule/empty-block.go
- testdata/empty-block.go
Closes #416 
Updated tests but as described in #424 we are currently incapable of testing on confidence level.
I've did some manual testing.
```
$ ./revive -config ./defaults.toml testdata/empty-block.go 
testdata/empty-block.go:13:2: this block is empty, you can remove it
testdata/empty-block.go:18:19: this block is empty, you can remove it
testdata/empty-block.go:26:9: this block is empty, you can remove it
testdata/empty-block.go:30:26: this block is empty, you can remove it
testdata/empty-block.go:34:6: this block is empty, you can remove it
$ ./revive -config ./defaults.toml testdata/empty-block.go 
testdata/empty-block.go:13:2: this block is empty, you can remove it
testdata/empty-block.go:18:19: this block is empty, you can remove it
testdata/empty-block.go:26:9: this block is …
```
> removes type-checking from empty-block rule

- README.md
revive is supported by ALE since PR(https://github.com/dense-analysis/ale/pull/2933). 
There's no need to define custom linter for revive.  Also, the repo name and URL have changed too. Update ALE section in readme.
> Update ALE configuratoin guide

- .github/workflows/lint.yaml
I made a stupid mistake! In an old version of [revive-action](https://github.com/morphy2k/revive-action) I have specified in the docker file to install the annotation binary via `go get` command without specifying a version. This now causes the old version to install the new incompatible binary.
This has been fixed in the latest version.
Big sorry!
**Edit:** In the meantime I have found a temporary solution and implemented it. The application uses a fallback value instead of exiting with an error.
> Bump revive-action from 1.3.3 to 1.4.0

- rule/blank-imports.go
- testdata/golint/blank-import-lib.go
- testdata/golint/blank-import-with-embed.go
Closes https://github.com/mgechev/revive/issues/500
> Ignore blank import of embed if embed is actually used in the file

- .github/workflows/release.yml
- .goreleaser.yml
- rule/blank-imports.go
- rule/struct-tag.go
**Why**
It should be handy to get revive binary without installing go.  also I want to add revive inside dockerfile without a dedicated stage to build the binary. So I will have a place to get binaries from (related to https://github.com/mgechev/revive/issues/489):
```zsh
curl -sL https://github.com/mgechev/revive/releases/download/vx.x.x/revive_x.x.x_OS.tar.gz | tar xz
```
**How**
With this PR, every time you create a tag, release github workflow runs to build binaries (linux, windows, mac) and upload them to releases section on github https://github.com/mgechev/revive/releases. It also add the changelog from commits.
> Add goreleaser & a gh workflow

- lint/config.go
- main.go
Closes #244 by adding an `exclude` field in the configuration. This field accepts an array of paths to exclude from the analysis. Path syntax is the same of that of the `-exclude` command line flag; for example the configuration
```toml
ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0
exclude = [
"rule/...",
"testdata/..."
]
``` 
will exclude the same files as if we execute `revive` with the following command line
```
revive -exclude rule/... -exclude testdata/... 
```
Excluding paths through command line flags overrides the configuration.
> adds "exclude" knob in configuration

- main.go
This PR adds a command to show version. goreleaser already pass these info during build time so [releases](https://github.com/mgechev/revive/releases) will have them by default from now on.
For manual builds, you can provide them:
```zsh
$ go build -v -ldflags="-X 'main.version=v1.0.0' -X 'main.commit=46f65914e3b26f7044ffe6842ecce10b58e2c2aa' -X 'main.date=2021-03-21T21:37:16Z' -X 'main.builtBy=goreleaser'"
$ ./revive --version
Current revive version v1.0.0 commit 46f65914e3b26f7044ffe6842ecce10b58e2c2aa, built @2021-03-21T21:37:16Z by goreleaser.
$ go build
$ ./revive --version
Current revive version dev commit none, built @unknown by unknown.
```
Closes #381
> Add version command to show binary build info

- README.md
Just wanted to add pyroscope to the list of happy users.
As a side-effect I also removed a trailing space
> Update the list of projects using revive

- .github/workflows/lint.yaml
I just released a [new major version](https://github.com/morphy2k/revive-action/releases/tag/v2.0.0) which, among other things, fixes the permission issue with PRs.
GitHub recently further restricted the permissions of the token, which severely limits the use when annotations are enabled. I switched to a [new alternative](https://github.com/morphy2k/revive-action/pull/48), this no longer requires direct access to the API.
> Bump revive-action to v2

- README.md
- RULES_DESCRIPTIONS.md
- config/config.go
- rule/nested-structs.go
- test/nested-structs_test.go
- testdata/nested-structs.go
Nested structs are awful to look at and I want to disallow them entirely in my projects.
Yes.
Yes.
TBD
Closes #529
> new rule: nested-structs

- rule/utils.go
This adds Unwrap to the "common methods" list as was done in https://go-review.googlesource.com/c/lint/+/221610 (PR https://github.com/golang/lint/pull/487).
Closes #546.
> Add Unwrap to common methods

- testdata/golint/exported.go
Add tests for the rule `exported` to cover the handling of common methods
> add tests on common methods handling

- rule/argument-limit.go
- rule/cognitive-complexity.go
- rule/cyclomatic.go
- rule/file-header.go
- rule/function-result-limit.go
- rule/line-length-limit.go
- rule/max-public-structs.go
- rule/utils.go
Provides better messages when a rule configuration error arises. 
Related to #561
> better messages for rules' config errors

- RULES_DESCRIPTIONS.md
Fix for "headers in rules" description doc, which I am using to create and validate automatic docs and checks for revive integration with `golangci-lint`
> fix: minor markdown issue with rules headers

- rule/file-header.go
Removes heaps allocation and unnecessary conversion, feels more "native"
> fix: switch to re.MatchString(string) instead re.Match([]byte(string))

- rule/time-naming.go
- test/time-naming_test.go
- testdata/time-naming.go
resolves #571
`time-naming` check misses few quite often used case.
> fix: `time-naming` issue  

- config/config.go
- config/config_test.go
- config/testdata/enable2.toml
- config/testdata/enable2OneSpecificSeverity.toml
- config/testdata/enableAll.toml
- config/testdata/enableAllBut2.toml
- config/testdata/enableAllOneSpecificSeverity.toml
- config/testdata/noRules.toml
Closes #577
Adds tests for configuration loading
> fixes issue #577

- README.md
- RULES_DESCRIPTIONS.md
- config/config.go
- rule/time-equal.go
- test/time-equal_test.go
- testdata/time-equal.go
> add new rule time equal 

- config/config.go
- config/config_test.go
- config/testdata/issue-585-defaultConfidence.toml
- config/testdata/issue-585.toml
Closes #585. Also fixes the "default config" test, which I believe should fail when `reflect.DeepEqual(cfg, tc.wantConfig) == false`.
> Fix config initialisation

- rule/error-strings.go
- testdata/golint/error-strings.go
Closes #610 by adding missing check on package.
> Fix package check in error-strings rule (#610)

- RULES_DESCRIPTIONS.md
It is not clear, why var-naming rule force users to write HTTP instead of Http. I've updated documentation about that.
> var-naming rule: note about initialisms

- RULES_DESCRIPTIONS.md
- rule/context-as-argument.go
- rule/utils.go
- test/context-as-argument_test.go
- test/golint_test.go
- testdata/context-as-argument.go
This allows users to configure a set of types that may appear before
`context.Context`.
Notably, I think this rule is useful for allowing the `*testing.T` type
to come before `context.Context`, though there may be other uses (such
as putting a tracer before it, etc).
See #605 for a little more context on this.
Fixes #605
> Allow whitelist for the context parameter check

- rule/cyclomatic.go
- testdata/cyclomatic-2.go
- testdata/cyclomatic.go
`cyclomatic` and `cognitive-complexity` are quite similar rules, but `cognitive-complexity` currenly showing `max enabled` so programmer don't need to open configs and check whats complexity level is targeted, however `cyclomatic` is missing this information.
I have updated tests.
Yes.
```diff
-main.go:17:1: cyclomatic: function j has cyclomatic complexity 3 (revive)
+main.go:17:1: cyclomatic: function j has cyclomatic complexity 3 (> max enabled 1) (revive)
main.go:17:1: cognitive-complexity: function j has cognitive complexity 2 (> max enabled 1) (revive)
main.go:17:1: cyclomatic complexity 3 of func `j` is high (> 1) (gocyclo)
main.go:17:1: cognitive complexity 2 of func `j` is high (> 1) (gocognit)
```
> refactor(cyclomatic): improved message for `cyclomatic` rule

- README.md
- lint/linter.go
- main.go
- test/utils.go
Closes #624 by adding a command line flag `max_open_files` to limit the number of open files.
By default, the flag is set to 0 (unlimited)
> Max open files

- rule/constant-logical-expr.go
- testdata/constant-logical-expr.go
Fixes the implementation for `constant-logical-expr` where logic handling for `token.LEQ` and `token.GEQ` operators is incorrect.
Fixes: #641
> Incorrect handling of token.{LEQ,GEQ} for constant-logical-expr

- rule/range-val-address.go
- testdata/range-val-address.go
This pr will improve the range-val-address rule. i added tests to display the issue.
#513
> range-val-address: improve detection

- README.md
- RULES_DESCRIPTIONS.md
- config/config.go
- rule/use-any.go
- test/use-any_test.go
- testdata/use-any.go
GO 1.18 includes a type alias for `interface{}`: `any`.
Now, the whole codebase of GO uses `any` in place of `interface{}`
This rule spots instances of `interface{}` and proposes to change it into `any`
Refs: [GO 1.18 release note](https://tip.golang.org/doc/go1.18) and [GO codebase commit replacing ìnterface` by `any`](https://github.com/golang/go/commit/2580d0e08d5e9f979b943758d3c49877fb2324cb)
> adds rule use-any

- Makefile
Since 1c283837a98f60bbb58746d96cb62c024c8dec3a build info variables
are defined in "github.com/mgechev/revive/cli", not "main".
Fixes #666
> Makefile: fix VERSION_FLAGS

- rule/redefines-builtin-id.go
Noticed during migration from our heavily modified "go-lint" to "revive" that there is an additional line printed. I am unsure that the convention for this project is on this, we do not allow adding such a call.
> Remove debugging output

- README.md
- RULES_DESCRIPTIONS.md
- config/config.go
- rule/datarace.go
- test/datarace_test.go
- testdata/datarace.go
The paper [A Study of Real-World Data Races in Golang](https://arxiv.org/abs/2204.00764) describes the most common sources of data-races in GO programs.
This rule detects two of these cases:
1. capture of named return
2. capture-by-reference of loop range variable
Even if after testing the rule against big open source projects (kubernetes, prometheus, GO, ...) a low rate of false positives were detected, some are expected due to the type-less nature of the rule (for example a go-routine capturing a named return of type `chan` will trigger a failure even if it is not a data-race)
While testing the rule, some data-races were detected in repositories like [Prometheus](https://github.com/prometheus/prometheus/issues/10570), [minio](https://github.com/minio/minio-go/pull/1634) and …
> add rule datarace

- rule/var-naming.go
Setting the entire file AST as the node causes golangci-lint to print the entire file source as the context, and line and column numbers set to 1. Point to the package name node instead.
Closes #688
> fix(var-naming): set node to package name for underscore in package name

- .github/workflows/build.yaml
- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- internal/typeparams/typeparams.go
- internal/typeparams/typeparams_go117.go
- internal/typeparams/typeparams_go118.go
- lint/package.go
- rule/exported.go
- rule/receiver-naming.go
- rule/unexported-return.go
- rule/utils.go
- test/receiver-naming_test.go
- testdata/receiver-naming-issue-669.go
This PR adds a new `internal/typeparams` package that provides support for type parameters when revive is built with Go 1.18 and higher.
It fixes an issue with `receiver-naming` rule being unable to parse receiver type from AST method declarations the receiver has type parameters.
Closes #669
> fix(receiver-naming): distinguish types with parameters

- README.md
- rule/error-strings.go
- test/error-strings-custom-functions_test.go
- testdata/error-strings-with-custom-functions.go
**Please, describe in details what's your motivation for this PR**
As mentioned in #697, we may use other error packages instead of builtin or pkg
and also want to lint those error messages with `revive`, so it will be good to
allow to customize the function name.
Closes #697
> Allow to customize user functions in rule `error-strings`

- rule/struct-tag.go
- testdata/struct-tag.go
> Check whether the tag name is duplicate or not

- rule/unreachable-code.go
- testdata/unreachable-code.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
Closes  #710
> add testing.FailNow  and related function to unreachable check

- README.md
- RULES_DESCRIPTIONS.md
An entry was missing in the reference documentation when using enableAllRules
The problem exists since banned-characters was added (#532 #591)
No tests added, only documentation was updated
Closes #729
> fix documentation about enableAllRules minimal config file

- PULL_REQUEST_TEMPLATE.md
- README.md
- rule/unconditional-recursion.go
Fix typos in various files: documentation, github template, and unconditional-recursion.go rule
> fix some typos in repository

- rule/nested-structs.go
- testdata/nested-structs.go
> fix #744: `chan struct{}` triggers nested-structs error

- .github/ISSUE_TEMPLATE/bug_report.md
- DEVELOPING.md
This PR updates `go get` references in the `bug_report.md` issue template and `DEVELOPING.md` files.
--- 
closes https://github.com/mgechev/revive/issues/737
> "go get" reference updates

- rule/identical-branches.go
This PR optimizes branch comparison by avoiding unnecessary calls to the expensive `gofmt`
That is done by checking the number of statements on each branch before calling `gofmt`. If branches have not the same number of statements then they are necessarily not identical.
> Speedup branch comparison in `identical-branches` rule

- RULES_DESCRIPTIONS.md
- rule/string-format.go
- test/string-format_test.go
Adds a syntactic mean to _negate_ the regular expressions in the configuration to pass from a "accept if match" to "fail if match" mode.
Now, using a `!` the configuration meaning is inverted
with "/^[A-Z].*$/" the rule will accept strings starting with capital letters
with "!/^[A-Z].*$/" the rule will a fail on strings starting with capital letters
Closes #762
> Allows inversing the semantics of `string-format` rule configurations

- README.md
- RULES_DESCRIPTIONS.md
- rule/early-return.go
- testdata/early-return.go
This PR aims to improve the `early-return` rule per issue [#775](https://github.com/mgechev/revive/issues/775). The main idea is avoid a false positive on constructions of the form:
```go
if A {
X()
} else if B {
Y()
} else {
Z()
return
}
```
We cannot reduce nesting by inverting `B` and de-indenting `Y()` here, because it would induce a change in program behaviour:
```go
if A {
X()
} else if !B {
Z()
return
}
Y() // now this is also called when A is true
```
The restructured code keeps track of whether we've encountered any prior branches on the if-else chain that would flow onto the following code, and suppresses the warning if so.
Also includes a few other quality of life improvements:
- If the if-initializer declares a variable, the text now mentions that moving the declaration onto …
> Fix early-return false positive and other tweaks

- rule/package-comments.go
This reduces the amount of lines reported by package-comments by only reporting the `package xyz` line, instead of the whole file.
Closes #790
> refactor: Reduce package-comments output scope

- rule/redefines-builtin-id.go
- testdata/redefines-builtin-id.go
> fix issue #792

- rule/var-naming.go
- testdata/golint/pkg-caps.go
This adds the implementation of golint's package name MixedCaps check from https://github.com/golang/lint/pull/285 as well as the [same testdata file used in golint, pkg-caps.go](https://github.com/golang/lint/blob/master/testdata/pkg-caps.go). Slightly improves "drop-in replacement for golint" story for golint's `lintNames()` rules.
Closes #796
> add golint's package name MixedCaps rule

- README.md
- RULES_DESCRIPTIONS.md
- rule/struct-tag.go
- test/struct-tag_test.go
- testdata/struct-tag-useroptions.go
Adds arguments to struct-tag rule to allow users define their own options
Closes #520
> fix issue #520

- revivelib/core_test.go
fix tests not passing after the modif of the default rules list
> fix tests not passing after the modif of the default rules list

- rule/empty-block.go
- testdata/empty-block.go
Fix false positive for common use-case of looping over a function with side-effects mentioned in https://github.com/mgechev/revive/issues/810.
closes #810
> Prevent empty-block when looping over call expr

- revivelib/core.go
This PR fixes a typo in the error message.
> fix: typo in error message when failed to get lint rules

- RULES_DESCRIPTIONS.md
_< !-- If you're fixing a typo or improving the documentation, you may not have to open an issue. -->_
The example for `[rule.add-constant]` was invalid TOML.
Instead of `"ignoreFuncs": "foo"` it should be `ignoreFuncs = "foo"`.
(Also added some spacing for improved readability.)
> Docs: Fix invalid toml in rule.add-constant example

- README.md
- rule/argument-limit.go
- rule/banned-characters.go
- rule/cognitive-complexity.go
- rule/cyclomatic.go
- rule/file-header.go
- rule/function-length.go
- rule/function-result-limit.go
- rule/line-length-limit.go
- rule/max-public-structs.go
Closes #749 
By adding (very opinionated) defaults to the following rules:
1. argument-limit (8)
2. banned-characters (none)
3. cognitive-complexity (7)
4. cyclomatic (10)
5. file-header (none)
6. function-length (50 statements, 75 lines)
7. function-result-limit (3)
8. line-length-limit (80)
9. max-public-structs (5)
These defaults will allow to run revive with a minimal configuration
```toml
ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0
enableAllRules = true
```
> adds default config to enable all rules work out of the box

- README.md
- RULES_DESCRIPTIONS.md
- internal/ifelse/args.go
- internal/ifelse/branch.go
- internal/ifelse/branch_kind.go
- internal/ifelse/chain.go
- internal/ifelse/rule.go
- rule/early-return.go
- rule/indent-error-flow.go
- rule/superfluous-else.go
- test/early-return_test.go
- test/superfluous-else_test.go
- testdata/early-return-scope.go
- testdata/superfluous-else-scope.go
The idea is to give users a option to suppress prompts of the kind indicated in [#816](https://github.com/mgechev/revive/issues/816), where the benefit of refactoring may not obviously outweigh the cost of increasing variable scope.
The logic as it stands, is that the `early-return` / `indent-error-flow` / `superfluous-else` rule will be skipped if `preserveScope` is given as a configuration argument and:
- At least one if the `if` blocks in the chain has an `if`-initializer (i.e. we bring variables defined in the initializer into the surrounding scope), or
- The block to be de-indented contains at least one declaration (i.e. we bring variables defined at the top level of the "if" or "else" branch body into the surrounding scope), and
- The if-else chain is not located at the end of its …
> ifelse: option to preserve variable scope

- RULES_DESCRIPTIONS.md
The example for configuring `early-return` arguments mistakenly refers to the `exported` rule.
> Fix typo in example documentation for early-return

- README.md
- config/config.go
- defaults.toml
- revivelib/core_test.go
The `if-return` rule was originally a golint rule which was removed from their ruleset for being out of scope. Similarly, it was dropped from revive intentionally as a result of #537. More recently, it was reintroduced into the default ruleset as a result of #799 due to a discrepancy in documentation without a discussion of whether this rule in particular belonged as a part of that default rule set.
While it is no longer a goal of this project to align 100% with the golint defaults, I believe that this rule gives bad advice often enough that it should not be enabled by default.
For example, consider the following code:
```go
if err := func1(); err != nil {
return err
}
if err := func2(); err != nil {
return err
}
if err := func3(); err != nil {
return err
}
return nil
```
The `if-return` …
> Drop if-return from default ruleset

- rule/string-format.go
- test/string-format_test.go
- testdata/string-format.go
This MR fix issue #839. Here the called object method is inside a structure (common pattern for dependency injection). Before the rule was not running for this rules.
The only thing is the function scope is tied to the structure name of the object, not to the object name.
This MR tries to fix this. A test was added to the string-format to evaluate this.
Closes #839
> fix: support method call from structures for string-format

- RULES_DESCRIPTIONS.md
- rule/var-naming.go
- test/var-naming_test.go
- testdata/var-naming_upperCaseConst-false.go
- testdata/var-naming_upperCaseConst-true.go
it's improvement for  #851 task
> imporve `var-naming`  - add upperCaseConst  option to allow UPPER_CASED constants #851

- rule/imports-blacklist.go
This PR removes a condition that prevents import-blacklist from checking go test files (closes #860).
> Allow import-blacklist to run against go test files

- RULES_DESCRIPTIONS.md
- rule/unused-param.go
- rule/unused-receiver.go
- test/unused-param_test.go
- test/unused-receiver_test.go
- testdata/unused-param-custom-regex.go
- testdata/unused-receiver-custom-regex.go
Now can provide custom regexes for `unused-parameter` and `unused-receiver` to allow names matching some regex, no just `_` itself (does'nt break default behavior)
```toml
[rule.unused-parameter]
Arguments = [ { allowRegex = "^_" } ]
[rule.unused-receiver]
Arguments = [ { allowRegex = "^_" } ]
```
> extended [allowRegex] parameter for `unused-parameter` and `unused-receiver` rules

- .gitignore
- README.md
- config/config.go
- config/config_test.go
- config/testdata/rule-level-exclude-850.toml
- lint/config.go
- lint/file.go
- lint/filefilter.go
- lint/filefilter_test.go
- test/file-filter_test.go
- testdata/file-to-exclude.go
Rule-level file exclude filter feature implementation #850
Tryed to keep project at max compatibility level.
But where are some changes in core structures.
Filters are prechecked and initialized after reading from TOML, so it could cause error.
So `Initialize() error` method added to RuleConfig
Logically it should be applyed in `normalize...`  part of GetConfig, but just parse can return error, not normalize, so
added call of initialization to `parse` part of GetConfig
All tested.
Closes #850
> per-rule file exclude filters (#850)

- rule/var-naming.go
- testdata/var-naming_upperCaseConst-false.go
- testdata/var-naming_upperCaseConst-true.go
`var-naming` rule with `upperCaseConst=true` now allows to use private uppercase constants
Closes #865
> (var-naming) support private uppercase constants #865

- rule/time-equal.go
- testdata/time-equal.go
> fix #846: time-equal garbled message when time returned from function

- rule/confusing-naming.go
- testdata/confusing-naming1.go
> fix #864: confusing-naming FP on methods of generic types

- rule/var-naming.go
- testdata/golint/var-naming.go
This PR proposes the removal of `k[A-Z][A-Za-z\d]*$` sub-rule from `var-naming`, as it doesn't clearly justify the reason for the check and fails to properly tackle any potential issues with [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation).
The emphasis is on ensuring clarity, reducing confusion, and enhancing the overall user experience for revive users.
The sub-rule originates from [golang/lint](https://github.com/golang/lint/blob/master/lint.go#L587) and has in the past led to false positives and confusion, see https://github.com/golang/lint/issues/258.
Closes #867
> resolve #867: remove k[A-Z][A-Za-z\d]*$ sub-rule from `var-naming`

- rule/use-any.go
- testdata/use-any.go
> Revert "fix: unnecesary alert for use-any when comments inside interface{}"

- rule/function-length.go
This PR fixes missing `defer` when calling `r.Unlock()`.
> fix: add missing defer when unlocking mutex

- README.md
- RULES_DESCRIPTIONS.md
- config/config.go
- go.sum
- rule/unchecked-type-assertion.go
- test/unchecked_type_assertion_test.go
- testdata/unchecked-type-assertion-accept-ignored.go
- testdata/unchecked-type-assertion.go
Closes #888 
Unchecked type assertions results can (and will) result in an unexpected panic and should be a lint.
This new rule covers this with configurable non-default option to ignore `foo, _ := bar.(Baz)` - cases where the `ok` value is ignored. 
See tests.
> Add unchecked-type-assertion

- rule/unchecked-type-assertion.go
Minor refactor of unchecked-type-assertion rule implementation
> quit asap config, remove unused pkg info

- README.md
- RULES_DESCRIPTIONS.md
- config/config.go
- rule/enforce-map-style.go
- test/enforce-map-style_test.go
- testdata/enforce-map-style-any.go
- testdata/enforce-map-style-literal.go
- testdata/enforce-map-style-make.go
> feat: add support for enforce-map-style rule 

- go.sum
pushes the go.sum resulting from a `go mod tidy`
> updates checksums

- RULES_DESCRIPTIONS.md
Fix a wrong copy-paste.
Off-topic: the versions of revive don't follow semver, is it expected?
- [v1.3.4](https://github.com/mgechev/revive/releases/tag/v1.3.4) contains enhancements
- [v1.3.3](https://github.com/mgechev/revive/releases/tag/v1.3.3) contains enhancements
> doc: fix examples

- README.md
- RULES_DESCRIPTIONS.md
- config/config.go
- rule/enforce-slice-style.go
- test/enforce-slice-style_test.go
- testdata/enforce-slice-style-any.go
- testdata/enforce-slice-style-literal.go
- testdata/enforce-slice-style-make.go
> feat: add support for enforce-slice-style rule

- cli/main.go
- config/config.go
- formatter/checkstyle.go
- formatter/doc.go
- lint/config.go
- lint/doc.go
- logging/logger.go
- main.go
- revivelib/core.go
- rule/comment-spacings.go
- rule/confusing-naming.go
- rule/defer.go
- rule/doc.go
- rule/struct-tag.go
- test/comment-spacings_test.go
- test/doc.go
- test/utils.go
Removes some issues detected by `revive` itself.
> Code cleaunp

- revivelib/core_internal_test.go
- rule/add-constant.go
- rule/constant-logical-expr.go
- rule/datarace.go
- rule/early-return.go
- rule/enforce-map-style.go
- rule/enforce-slice-style.go
- rule/indent-error-flow.go
- rule/superfluous-else.go
PR related with #904 
all unused functions parameters and receivers have been replaced with undersorce (_) sign to supress warnings. Maybe there is more elegant way to do this, but I dont want to remove parameters declaration 
test command: `revive -config ~/revive.toml -formatter stylish {test,rule,revivelib}`
config: 
```
ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0
[rule.unused-parameter]
[rule.unused-receiver]
```
> cleanup: rename unused parameters and receivers to _

- rule/unconditional-recursion.go
- test/utils.go
- testdata/unconditional-recursion.go
related with issue #902
fix is simple, we should add `case *ast.FuncLit` in rule: rule/unconditional-recursion.go , and return nil, then test pass. 
but at the end I dont know if I should add some additional code as in previous cases for ex: `w.updateFuncStatus(n.Body)` but if test pass it should be ok :P
> fix: literal calls case

- testdata/unhandled-error-w-ignorelist.go
io/ioutil has been deprecated since Go 1.16
https://pkg.go.dev/io/ioutil
Ignore unused error in `os.WriteFile` call - already set to be ignored in https://github.com/mgechev/revive/blob/8dbd58748ae8bc7d95a884fd8012c0c56c4efdff/test/unhandled-error_test.go#L18
> refactor: remove refs to io/ioutil

- README.md
- RULES_DESCRIPTIONS.md
- config/testdata/enableAllBut2.toml
- testdata/confusing-results.go
- testdata/duplicated-imports.go
- testdata/golint/error-strings.go
cleanup in few files containing trailing whitespace and incorrect end line
no tests needed
> Fix trailing whitespaces

- revivelib/core_test.go
related with #925 
when we ignore color markers/command before formatter starts, then output text should be identical with compared text :P
> fix:ignore color marks when compare stings in test

- formatter/default.go
- formatter/formatter_test.go
- formatter/friendly.go
- formatter/ndjson.go
- formatter/plain.go
- formatter/unix.go
This resolves the issue I raised in #920. It also adds a test for formatters. There weren't tests previously, so I added just enough to demonstrate the issue is resolved.
Closes #920
> formatters return output

- README.md
- RULES_DESCRIPTIONS.md
- rule/import-alias-naming.go
- test/import-alias-naming_test.go
- testdata/import-alias-naming-custom-config-with-multiple-values.go
- testdata/import-alias-naming-custom-config-with-only-deny.go
This PR provides an extension to the existing `import-alias-naming` rule. While it preserves the backwards compatible configuration, with which it is possible to define an _allow_ regex pattern for import aliases, this PR brings a way to configure any or both pattern types: `allowRegex` and/or `denyRegex`. This brings two types of configuration:
1. The original one, allow pattern:
```toml
[rule.import-alias-naming]
arguments = ["^[a-z][a-z0-9]{0,}$"]
```
2. The new one, both allow and deny patterns:
```toml
[rule.import-alias-naming]
arguments = [ { allowRegex = "^[a-z][a-z0-9]{0,}$", denyRegex = '^v\d+$' } ]
```
Closes #924.
> Add denyRegex support for import-alias-naming rule

- rule/var-naming.go
We should use `(*regexp.Regexp).MatchString` instead of `(*regexp.Regexp).Match([]byte(...))` when matching string to avoid unnecessary `[]byte` conversions and reduce allocations. A one-line change for free performance improvement.
Example benchmark:
```go
func BenchmarkMatch(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := upperCaseConstRE.Match([]byte("FOO_BAR")); !match {
b.Fail()
}
}
}
func BenchmarkMatchString(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := upperCaseConstRE.MatchString("FOO_BAR"); !match {
b.Fail()
}
}
}
```
```
goos: linux
goarch: amd64
pkg: github.com/mgechev/revive/rule
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkMatch-16          	 5248138	       285.8 ns/op	       8 B/op	       1 allocs/op
BenchmarkMatchString-16    	 6899334 …
```
> var-naming: avoid allocations with `(*regexp.Regexp).MatchString`

- cli/main_test.go
This PR refactors tests in `cli/main_test.go`.
1. Replace `os.Setenv` with [`t.Setenv`](https://pkg.go.dev/testing#T.Setenv);
2. Replace `init()` with [`TestMain`](https://pkg.go.dev/testing#hdr-Main).
3. Use [`t.Cleanup`](https://pkg.go.dev/testing#T.Cleanup) for reseting `AppFs`.
`T.Setenv` calls `os.Setenv` and uses `Cleanup` to restore the environment variable to its original value after the test.
`Cleanup` registers a function to be called when the test and all its subtests complete.
`TestMain` is a handy way to do extra setup or teardown before or after a test executes.
> refactor: cli tests: use TestMain, t.Setenv, t.Cleanup

- rule/datarace.go
- rule/flag-param.go
- rule/modifies-value-receiver.go
- rule/optimize-operands-order.go
- rule/unconditional-recursion.go
- rule/unused-param.go
- rule/unused-receiver.go
- rule/utils.go
This PR refactors internal function: remove the parameter `f func(n ast.Node) []ast.Node` from `pick` because it is always `nil`.
This refactoring was found by the [`unparam`](https://github.com/mvdan/unparam) linter:
```sh
❯ go run mvdan.cc/unparam@latest ./...
lint/file.go:191:22: (*File).disabledIntervals$3 - filename is unused
lint/file.go:191:95: (*File).disabledIntervals$3 - result 0 ([]github.com/mgechev/revive/lint.DisabledInterval) is always nil
rule/utils.go:98:54: pick - f always receives nil
exit status 1
```
> refactor: remove unused parameter from pick function

- go.sum
- rule/import-alias-naming.go
- testdata/import-alias-naming.go
This PR addresses the issue raised in #937
> fix: ignore dot import aliases in import-alias-naming rule

- RULES_DESCRIPTIONS.md
- rule/dot-imports.go
- test/dot_imports_test.go
- testdata/import-dot.go
Add the ability to allow list of packages to be dot imported.
Add a new don-imports configuration:
* `allowedPackages`: (list of strings) comma-separated list of allowed dot import packages
Example:
```toml
[rule.dot-imports]
arguments = [{ allowedPackages = ["github.com/onsi/ginkgo/v2","github.com/onsi/gomega"] }]
```
Fixes #923
> [dot-imports] support allow list of packages

- test/json-data-format_test.go
- test/utils.go
- testdata/json-data-format-atomic.go
- testdata/json-data-format-var-naming.go
related with #424 
now we can use instead of txt format:
`x = atomic.AddUint64(&x, 1)        // MATCH /direct assignment to atomic value/`
json format:
`x = atomic.AddUint64(&x, 1) // json:{"MATCH": "direct assignment to atomic value","Confidence": 1}`
of course this is only draft because I dont know how it should looks like logic to use all Failure properties, so I asume that for example we want to check if Confidence property have value equal to that setted up in json object, and if value is not equal then throw/log error otherwise everything is ok
this draft dont remove old MATH txt format, but add json feature, so we can use old format for some time :)
@chavacava what do you think about?
> extend parsing instructions to use json object instead of plain txt

- rule/modifies-value-receiver.go
- testdata/modifies-value-receiver.go
Assignments which index into the slice or map are already ignored on line 72, and those where the whole receiver is slice or map on line 50. We should not ignore assignments where the member variable is slice or map.
Closes #942
> modifies-value-receiver: warn on slice or map

- rule/add-constant.go
- testdata/add-constant.go
> fix: add-constant struct tags in anonymous struct literals false positive

- rule/unhandled-error.go
- testdata/unhandled-error-w-ignorelist.go
This PR updates the error message used by the `unhandled-error` rule to use
the full function name. The full function name matches the name used to
evaluate ignored functions in the configuration, therefore it's friendlier to
users to wish to configure an exlusion based on an error message.
The error message is sufficiently covered by existing tests, which are updated
in this PR.
Closes: #961
> unhandled-error: use full function name in error message

- .gitignore
- lint/utils.go
- testdata/var-naming.go
`var-naming` does not check that ID is capitalised when it is plural such as IDs. For example if I have `uIds := []string{}` it will allow this var name where really it should return var `uIds should be uIDs`.
Closes #947
> feat: capitalise var naming to IDs

- rule/unused-param.go
- testdata/unused-param.go
Closes #965
See #965 for the motivation behind this PR.
This does potentially significantly change the performance of this rule because we will now walk into the function bodies. If we are concerned about a performance regression here I think an alternative could be to either add a new rule or add a configuration to the rule to gate checking anonymous functions.
> Check function literals in `unused-param`

- README.md
- RULES_DESCRIPTIONS.md
- config/config.go
- rule/max-control-nesting.go
- test/max-control-nesting_test.go
- testdata/max-control-nesting.go
This PR adds rule `max-control-nesting`, the GO implementation of https://sonarsource.atlassian.net/browse/RSPEC-134
> Adds rule `max-control-nesting`

- config/config.go
Related to #953
Related to https://github.com/golangci/golangci-lint/issues/4353
> fix: add enforce-repeated-arg-type-style in config

- RULES_DESCRIPTIONS.md
- rule/comment-spacings.go
- test/comment-spacings_test.go
- testdata/comment-spacings.go
**Please, describe in details what's your motivation for this PR:**
Some projects like Kubebuilder have markers that do not follow the pattern //name:, e.g.: //+optional. Due to a colon added at the end of the values when parsing the arguments, revive complains about comments starting with the marker even if one adds it as an exception.
**Did you add tests?**
The current tests are still valid with the changes.
**Does your code follow the coding style of the rest of the repository?**
Yes.
Closes #980
> Remove added colon in `comment-spacings` rule

- README.md
- RULES_DESCRIPTIONS.md
- config/config.go
- rule/comments-density.go
- test/comments-density_test.go
- testdata/comments-density-1.go
- testdata/comments-density-2.go
- testdata/comments-density-3.go
This PR adds a new rule `comments-density`.
The rule is inspired on the SonarQube rule on the [_comment lines density_ metric](https://docs.sonarsource.com/sonarqube/latest/user-guide/metric-definitions/)
The default argument value of the rule is `0`, i.e. the rule is de-facto deactivated, to avoid polluting analysis of those using `enableAllRules = true` in the configuration.
> adds `comments-density` rule

- rule/utils.go
- testdata/comment-spacings.go
Improves regular expression for handling cases like 
`//this is a regular command that's incorrectly formatted //nolint:foobar // because one two three`
> more precise regular expression for directive comments

- rule/confusing-naming.go
- testdata/confusing-naming1.go
Fix logic to handle expressions that include pointers to generic types.
Add test data
Closes https://github.com/mgechev/revive/issues/982
> Fix false positive confusing-naming error on generics with pointer type receiver

- RULES_DESCRIPTIONS.md
- add missing `enforce-repeated-arg-type-style` TOC item
- fix typos:
- `GO` -> `Go`
- `yaml` -> `toml`
- `[imports-blocklist]` -> `[rule.imports-blocklist]`
- use the same style for all the configuration examples
> docs: missing item and homogeneous style

- RULES_DESCRIPTIONS.md
- add missing lines
- add missing `[rule.` prefix
- change rule order
Fixes #991
> docs: clean rule descriptions

- lint/config.go
- lint/linter.go
* Support go workspaces when detecting the go version.
* Do not invoke go list for every package.
Closes  #995
> Fix a performance regression #995

- README.md
- rule/comments-density.go
- Fix the Docker image version. The `v1.1.2-next` tag is not available, so we can use the latest released version: `v1.3.7`
- Fix some problems with syntax and grammar
- Fix typo for `minimum` word
> Update README.md & Typo

- .github/workflows/release.yml
Problem:
```
Run goreleaser/goreleaser-action@v2
Downloading https://github.com/goreleaser/goreleaser/releases/download/v2.1.0/goreleaser_Linux_x86_64.tar.gz
Extracting GoReleaser
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/c41b664f-359e-4cdb-b355-4bb23158e448 -f /home/runner/work/_temp/5e7de14d-460b-41c5-a406-e2cf60039cc8
GoReleaser latest installed successfully
v1.3.8 tag found for commit '7ef710a'
/opt/hostedtoolcache/goreleaser-action/2.1.0/x64/goreleaser release --rm-dist
⨯ command failed                                   error=unknown flag: --rm-dist
Error: The process '/opt/hostedtoolcache/goreleaser-action/2.1.0/x64/goreleaser' failed with exit code 1
```
See: https://goreleaser.com/deprecations/#-rm-dist …
> fix: goreleaser uses unknown flag: `--rm-dist` 

- .github/workflows/release.yml
This PR bumps goreleaser version to 1.22.
> Update goreleaser version to 1.22

- lint/package.go
- rule/redefines-builtin-id.go
- testdata/redefines-builtin-id.go
Close #1021 
go1.21 has introduced new functions `clear`, `max` and `min`.
It would be nice revive checks these functions in redefines-builtin-id rule on go1.21+.
> check clear/max/min in redefines-builtin-id rule on go1.21+

- rule/redefines-builtin-id.go
- testdata/redefines-builtin-id.go
Close #1022 
Currently, function related variables (param, result, and type param) are not checked by `redefines-builtin-id rule`.
It would be nice if revive reports `redefinition of the built-in ...` errors for function related variables.
> check param, result, type param of function in redefines-builtin-id rule

- lint/linter.go
Closes #1027 by using a default Go version as a fallback in case of absence of a `go.mod` file for the package under analysis.
> use a default Go version (1.0) in absence of go.mod

- CONTRIBUTING.md
- rule/exported.go
- rule/import-alias-naming.go
- rule/unchecked-type-assertion.go
- test/utils_test.go
- testdata/comment-spacings.go
- testdata/exported-issue-1002.go
- testdata/unchecked-type-assertion-accept-ignored.go
The PR corrects spelling mistakes in comments and docs.
> docs: fix typo in comments

- RULES_DESCRIPTIONS.md
The PR replaces no longer valid `https://github.com/golang/go/wiki/CodeReviewComments` with `https://go.dev/wiki/CodeReviewComments`.
The Go wiki on GitHub has been moved to go.dev in the golang/go#61940.
> docs: update Go wiki links

- .gitignore
- lint/file.go
- rule/datarace.go
Fix lint issues reported by revive
```sh
revive ./...
lint/file.go:191:22: parameter 'filename' seems to be unused, consider removing or renaming it as _
rule/datarace.go:83:3: var getIds should be getIDs
```
> fix lint issues

- go.mod
- go.sum
- revivelib/core.go
- test/utils_test.go
The PR replaces the package `github.com/pkg/errors` with native error wrapping.
The package [github.com/pkg/errors](https://github.com/pkg/errors) is archived from Dec 1, 2021 due to the existence of Go native error wrapping.
> Move away from deprecated github.com/pkg/errors

- test/datarace_test.go
- test/file-filter_test.go
- test/golint_test.go
- test/range-val-address_test.go
- test/range-val-in-closure_test.go
- test/redefines-builtin-id_test.go
- test/utils_test.go
- testdata/go.mod
- testdata/go1.21/go.mod
- testdata/go1.21/redefines-builtin-id.go
- testdata/go1.22/datarace.go
- testdata/go1.22/go.mod
- testdata/go1.22/range-val-address.go
- testdata/go1.22/range-val-in-closure.go
Reorganizes testing infrastructure to enable testing rules under different go versions.
Now, `testdata` folder is organized by go version:
* At its root we find test files applicable for go versions >= 1.0 
* Under go1.21, files for go version >= 1.21
* Under go1.22, files for go version >= 1.22
This PR will make possible updating `revive` go version to 1.23 and keep test passing.
> adds tests for specific go versions

- README.md
- RULES_DESCRIPTIONS.md
- rule/receiver-naming.go
- test/receiver-naming_test.go
- testdata/receiver-naming-issue-1040.go
Closes #1040 
The rule receiver-naming now accepts an optional argument indicating the maximum length of receiver names. If no argument is provided the rule does not check for names length.
> adds check for receiver names length

- RULES_DESCRIPTIONS.md
- rule/enforce-repeated-arg-type-style.go
> fix: enforce-repeated-arg-type-style rule finds false positives in case of invalid types

- RULES_DESCRIPTIONS.md
- rule/enforce-repeated-arg-type-style.go
- testdata/enforce-repeated-arg-type-style-mixed-full-short.go
- testdata/enforce-repeated-arg-type-style-mixed-short-full.go
- testdata/enforce-repeated-arg-type-style-short-args.go
- testdata/enforce-repeated-arg-type-style-short-return.go
Closes #1032 by comparing string representations of types (and not relying on actual type information)
Failure messages were extended to provide the name of the type that can be omitted.
Failure position information were fixed to point to the type that can be omitted.
This new implementation of the rule spots more failures than the current implementation and it seems to not generate false positives.
The attached files contain the result of linting the `telegraf` codebase (cf #1032) with the current implementation and with the implementation proposed by this PR.
[pr-result.txt](https://github.com/user-attachments/files/17103498/pr-result.txt)
[head-result.txt](https://github.com/user-attachments/files/17103499/head-result.txt)
> fix #1032 by comparing string representations of types

- rule/function-result-limit.go
- rule/line-length-limit.go
- rule/max-control-nesting.go
- rule/max-public-structs.go
Removes redefinition of max built-in function to remove linting errors
> removes redefinition of max built-in

- rule/exported.go
- testdata/golint/const-block.go
Closes #1045 by making the exported rule behave as `golint` did.
The rule accepted documentation comments in the same line of variable/constant declarations while `golint` doesn't.
> Makes exported rule behave as golint

- .github/workflows/release.yml
- .goreleaser.yml
- Dockerfile
This PR improves the container image build process and introduces ARM64 images by using Buildx.
It also adds GitHub's [artifact attestations](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds#generating-artifact-attestations-for-your-builds) to make the images verifiable.
Closes #1069
> Enhance container build process

- lint/linter.go
- test/golint_test.go
- test/utils_test.go
The PR replaces the usages of [`path`](https://pkg.go.dev/path) package with [`path/filepath`](https://pkg.go.dev/path/filepath).
Because `path.Join` is for URL paths, and `filepath.Join` is for file paths.
> refactor: use "path/filepath" instead of "path"

- cli/main_test.go
- lint/filefilter_test.go
- revivelib/core.go
- rule/enforce-map-style.go
- rule/enforce-slice-style.go
- rule/line-length-limit.go
- rule/max-public-structs.go
- rule/redefines-builtin-id.go
- rule/var-naming.go
- test/json-data-format_test.go
- test/utils_test.go
- test/var-naming_test.go
The PR removes empty lines that don't add to readability.
> chore: remove unnecessary empty lines

- revivelib/core_internal_test.go
- revivelib/core_test.go
The PR replaces `t.Fatal(err.Error())` with `t.Fatal(err)` for to simplify tests and for consistency with other statements.
> refactor: change to t.Fatal(err)

- rule/dot-imports.go
- rule/var-naming.go
This PR simplifies code a bit by applying suggestions from the `early-return` rule.
> refactor: fix revive.early-return issues

- test/file-filter_test.go
The PR corrects a typo in the `WasApplyed` field name.
> refactor: fix typo in the field name of TestFileFilterRule

- test/utils_test.go
The PR fixes the function `extractInstructionFromJSON` used for tests. It should return an error, but just prints an error and returns `nil`.
> fix: extractInstructionFromJSON returns an error

- README.md
- RULES_DESCRIPTIONS.md
- config/config.go
- rule/filename-format.go
- test/filename-format_test.go
- testdata/filename-ok-default.go
- testdata/filename_with_underscores.go
- testdata/filenamе-with-non-ascii-char.go
Closes #1090 by adding a new rule with a broad scope of enforcing filename format
> adds filename-format rule

- .github/workflows/lint.yaml
- lint/package.go
- revive.toml
- rule/add-constant.go
- rule/comments-density.go
- rule/early-return.go
- rule/filename-format.go
- rule/indent-error-flow.go
- rule/superfluous-else.go
- test/utils_test.go
The PR adds `revive.toml` for linting revive codebase itself. Additionally, it fixes appeared lint issues.
> revive: add revive.toml for linting revive itself

- rule/use-any.go
- testdata/use-any.go
The PR changes the failure message for the `use-any` rule from `since GO 1.18 'interface{}' can be replaced by 'any'` to `since Go 1.18 'interface{}' can be replaced by 'any'`.
See ["Is the language called Go or Golang?"](https://go.dev/doc/faq#go_or_golang)
> fix: change "GO" to "Go" in the use-any rule

- revivelib/core_internal_test.go
- test/utils_test.go
This PR simplifies test code.
Explanation:
- `len(revive.lintingRules)` is `0` if `revive.lintingRules` is `nil`.
- The lambda `func(file string) ([]byte, error) { return os.ReadFile(file) }` can be simply `os.ReadFile`.
- Every case has an implicit `break` statement, which is familiar to every Go developer.
> refactor: simplify tests

- rule/string-format.go
The PR removes unused parameter in the `stringFormatSubrule.generateFailure` unexported function to fix the warning:
```
❯ revive -config revive.toml ./...
rule/string-format.go:310:47: parameter 's' seems to be unused, consider removing or renaming it as _
```
> refactor: remove unused parameter in unexported function

- lint/linter.go
- lint/package.go
`defer wg.Done()` called at the end of a function block, so it is need to use `defer`.
> refactor: remove redundant defer

- RULES_DESCRIPTIONS.md
This PR changes `Arguments` to `arguments` in a few examples for consistency with other rule examples in the `RULES_DESCRIPTIONS.md`.
> docs: lowercase `arguments` for consistency

- lint/linter.go
- lint/linter_test.go
The PR fixes #1120.
The problem is the `retrieveModFile` function, which hangs forever when `go.mod` is not found. `filepath.Dir` returns `C:/` on Windows, but the implementation expects `"."` or `"/"`.
The bug appeared after changing `path.Dir` to `filepath.Dir` in #1073. We can revert to using `path.Dir`, but a better solution is to add `strings.TrimPrefix(dir, filepath.VolumeName(dir))` for Windows.
> fix: revive hangs on Windows if go.mod is not found

- rule/max_public_structs.go
- test/max_public_structs_test.go
- testdata/max_public_structs.go
- testdata/max_public_structs_ok.go
> fix: fixes #1103 by fixing the processing of max-public-structs arguments

- formatter/default.go
- formatter/formatter_test.go
- formatter/friendly.go
- formatter/plain.go
- formatter/sarif.go
- formatter/stylish.go
- revivelib/core_test.go
This PR fixes the link to a rule description by replacing the string `https://revive.run/r#` with `https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#`. `revive.run` is [outdated](https://github.com/mgechev/revive.run/issues/60) and no longer contains descriptions for all rules.
Fixes #1062
> fix: rule description URL

- formatter/friendly.go
The PR refactors "friendly" formatter printing functions.
> refactor: remove redundant fmt.Fprintln calls

- RULES_DESCRIPTIONS.md
- revive.toml
- rule/filename_format.go
- testdata/filenamе_with_non_ascii_char.go
Just a quick fix for an obvious issue with the filename regex. Filename extension's dot wasn't escaped so, for example, "awesome$go" was considered a valid filename.
> Filename-format rule: fix filename extension regex: ".go" to "\\.go".

- config/config.go
The PR refactors `parseConfig` implementation to use [`toml.Unmarshal`](https://pkg.go.dev/github.com/BurntSushi/toml#Unmarshal) instead of [`toml.Decode`](https://pkg.go.dev/github.com/BurntSushi/toml#Decode). The first accepts the `data` as `[]byte`, the second as `string`. This removes one conversion between from `[]byte` to `string`.
Benchmark says that this refactoring saves one allocation without increasing `parseConfig` complexity.
<details><summary>Benchmarks</summary>
<p>
```go
func BenchmarkParseConfig(b *testing.B) {
var config lint.Config
configPath := filepath.Join("..", "full.toml")
b.ResetTimer()
for i := 0; i < b.N; i++ {
err := parseConfig(configPath, &config)
if err != nil {
b.Fatalf("failed to parse config: %v", err)
}
}
}
func BenchmarkParseConfigString(b *testing.B) { …
```
> refactor: use toml.Unmarshal instead of toml.Decode

- cli/main.go
- cli/main_test.go
The PR extracts some functionality to the `getVersion()` function and adds tests for it.
> refactor: extract getVersion function

- rule/blank_imports.go
- rule/bool_literal_in_expr.go
- rule/exported.go
- rule/utils.go
- rule/var_declarations.go
- rule/var_naming.go
This PR moves unexported functions and variable declarations from `utils.go` to rule files, where these functions are used. This increases cohesion, readability and rules maintainability.
Now, in the `utils.go` only functions that are common for a few rules.
> refactor: move functions and vars out from rule/utils.go

- rule/redundant_build_tag.go
micro-refactoring of the redundant-build-tag rule
> refactor: remove useless failure slice declaration

- rule/redundant_build_tag.go
Renames `arguments` into `_` in redundant-build-tag rule
> rename unused parameter

- README.md
- config/config.go
This PR extends README.md with the description of a few missing formatters. Also, sorts formatters list in the `config/config.go`.
> docs: add json, ndjson, checkstyle to "Available Formatters"

- README.md
- RULES_DESCRIPTIONS.md
- config/config.go
- rule/use_errors_new.go
- test/use_errors_new_test.go
- testdata/use_errors_new.go
Implementing a new rule `use-errors-new` that proposes replacing `fmt.Errorf` by `errors.New` when possible.
As indicated in [this issue](https://github.com/googleapis/google-cloud-go/issues/9749), beyond style considerations, `errors.News` is ~4x faster that `fmt.Errorf`
(initial discussion on this PR can be retrieved at #1136)
> adds rule use-errors-new

- rule/deep_exit.go
- rule/unconditional_recursion.go
- rule/utils.go
- rule/utils_test.go
The map `exitFunctions` is duplicated in `rule/deep_exit.go` and `rule/unconditional_recursion.go`, so I moved this `var` to `rule/utils.go`. Additionally, I extracted `isCallToExitFunction` to a separate function.
> refactor: avoid duplicated exitFunctions map

- RULES_DESCRIPTIONS.md
- internal/ifelse/args.go
- internal/ifelse/branch.go
- internal/ifelse/branch_kind.go
- internal/ifelse/chain.go
- internal/ifelse/func.go
- internal/ifelse/rule.go
- internal/ifelse/target.go
- rule/early_return.go
- rule/indent_error_flow.go
- rule/superfluous_else.go
- test/early_return_test.go
- testdata/early_return.go
- testdata/early_return_jump.go
- testdata/early_return_scope.go
This PR implements an extension to the `early-return` proposed in [#1133](https://github.com/mgechev/revive/issues/1133). Specifically, it suggest a rewrite of the form
```
if x {
y
}
```
to
```
if !x {
return|break|continue
}
y
```
In cases where
- the `if` statement is at the end of the surrounding function body, `for` loop, or `switch` / `select` branch
- it has no `else` clause attached
- the `if` block body consists of multiple statements
- the other common prerequisites for `early-return` are met
- the new behaviour has been opted into via a configuration argument
Closes #1133
> feat: optional extension to early-return rule (#1133)

- rule/deep_exit.go
This PR fixes pointer vs. non-pointer receiver type for `lintDeepExit`.
> deep-exit: fix mixed receiver type (lintDeepExit)

- README.md
Commit be95bfa70536af6446f2b077b323923e8ccb1d09 renamed `rule/argument-limit.go` to be `rule/argument_limit.go`. This PR adjusts sources to changes.
> docs: update `argument_limit.go` reference

- internal/astutils/ast_utils.go
- lint/package.go
- testdata/golint/sort.go
This PR resolves TODO comment that proposed to check sortable methods signatures.
* Ensures that only methods with the correct signature are identified as implementing required behavior (`sort.Interface`).
* Prevents accidental false positives from methods that happen to have the same name but differ in their functionality.
> chore: Improve sortables detection

- rule/deep_exit.go
- rule/deep_exit_test.go
- testdata/deep_exit_test.go
I propose to ignore testable [example functions](https://go.dev/blog/examples) in the `deep-exit` rule. There is nothing wrong with using `log.Fatal` or `log.Fatalf` in examples.
See these examples where using `log.Fatal` is normal:
- https://github.com/golang/go/blob/e5489a34ca2c31608821d3ac4ec07892fb6a2272/src/embed/example_test.go#L21
- https://github.com/google/go-github/blob/c6856bc9e29aeba0999a959f7a892098b18ff965/github/examples_test.go#L103
- https://github.com/golang/go/blob/e5489a34ca2c31608821d3ac4ec07892fb6a2272/src/image/decode_example_test.go#L28
> deep-exit: ignore testable examples

- rule/unused_param.go
- rule/unused_receiver.go
The option for `unused-param` and `unused-receiver` rules is `"allowRegex"`, not `"allowedRegex"`.
> unused-param,unused-receiver: fix panic message

- rule/unused_param.go
- rule/unused_receiver.go
- test/unused_param_test.go
- test/unused_receiver_test.go
The PR refactors the `configure` function in both `unused-param` and `unused-receiver`:
- change to use `blankIdentifierRegex` that is compiled once;
- reduce nested `if`s;
- add tests and benchmarks.
Benchmarks show that version in this PR has slightly fewer allocations.
```sh
$ git switch master
$ go test -benchmem -run=^$ -bench "^BenchmarkUnused.*" github.com/mgechev/revive/test -count=10 > old.txt
$ git switch refactor/unused-configure
$ go test -benchmem -run=^$ -bench "^BenchmarkUnused.*" github.com/mgechev/revive/test -count=10 > new.txt
$ benchstat old.txt new.txt
goos: darwin
goarch: arm64
pkg: github.com/mgechev/revive/test
cpu: Apple M1 Pro
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
UnusedParam-8      671.0µ ± 1% …
```
> unused-param,unused-receiver: refactor configure func

- rule/confusing_results.go
- testdata/confusing_results.go
This PR fixes the confusing-result problem on working with results of types other than plain types.
It also simplifies the rule implementation by replacing the AST visitor by an iteration over the declarations of the file.
> fix: confusing-results doesn't work with pointer types

- rule/cyclomatic.go
Simplifies cyclomatic rule by replacing AST walker by an iteration over global declarations
> refactor (rule/cyclomatic): replace AST walker by iteration over declarations

- rule/error_return.go
Simplifies error-return rule by replacing AST walker by an iteration over global declarations
>  refactor (rule/error-return): replace AST walker by iteration over declarations

- rule/argument_limit.go
- test/argument_limit_test.go
Simplifies arguments-limits rule by replacing AST walker by an iteration over global declarations
> refactor (rule/arguments-limits): replace AST walker by iteration over declarations

- rule/context_as_argument.go
Simplifies context-as-argument rule by replacing AST walker by an iteration over global declarations
> refactor(rule/context-as-argument): replace AST walker by iteration over declarations

- rule/flag_param.go
Simplifies flag-param rule by replacing AST walker by an iteration over global declarations
>  refactor (rule/flag-param): replace AST walker by iteration over declarations

- rule/function_length.go
Simplifies function-length rule by replacing AST walker by an iteration over global declarations
> refactor (rule/function-length): replace AST walker by iteration over declarations

- rule/modifies_value_receiver.go
Simplifies modifies-value-receiver rule by replacing AST walker by an iteration over global declarations
>  refactor (rule/modifies-value-receiver): replace AST walker by iteration over declarations

- rule/function_result_limit.go
Simplifies function-result-limit rule by replacing AST walker by an iteration over global declarations
> refactor (rule/function-result-limit): replace AST walker by iteration over declarations

- test/atomic_test.go
- test/bool_literal_in_expr_test.go
- test/call_to_gc_test.go
- test/confusing_naming_test.go
- test/constant_logical_expr_test.go
- test/defer_test.go
- test/early_return_test.go
- test/empty_block_test.go
- test/empty_lines_test.go
- test/identical_branches_test.go
- test/if_return_test.go
- test/modifies_param_test.go
- test/redefines_builtin_id_test.go
- test/redundant_import_alias_test.go
- test/string_of_int_test.go
- test/struct_tag_test.go
- test/superfluous_else_test.go
- test/time_equal_test.go
- test/time_naming_test.go
- test/unnecessary_stmt_test.go
- test/useless_break_test.go
The PR removes redundant comments in the `test` package that do not add much value to code readability.
> test: remove useless comments

- rule/unexported_return.go
Simplifies unexported_return rule by replacing AST walker by an iteration over global declarations
> refactor (rule/unexported-return): replace AST walker by iteration over declarations

- rule/unused_receiver.go
Simplifies unused-receiver rule by replacing AST walker by an iteration over global declarations
> refactor (rule/unused-receiver): replace AST walker by iteration over declarations

- rule/datarace.go
Simplifies datarace rule by replacing AST walker by an iteration over global declarations
> refactor (rule/datarace): replace AST walker by iteration over declarations

- rule/get_return.go
Simplifies get-return rule by replacing AST walker by an iteration over global declarations
> refactor (rule/get-return): replace AST walker by iteration over declarations

- rule/modifies_value_receiver.go
- testdata/modifies_value_receiver.go
Closes #1109 
Adds test for assignment operators
> fix(rule/modifies-value-receiver): miss modification by ++/--

- internal/astutils/ast_utils.go
- rule/confusing_results.go
- rule/datarace.go
removes:
```
internal/astutils/ast_utils.go:1:1: should have a package comment
rule/datarace.go:52:1: exported method DataRaceRule.ExtractReturnIDs should have comment or be unexported
rule/confusing_results.go:30:53: extra empty line at the start of a block
```
> refactor: remove lint issues

- internal/astutils/ast_utils.go
- testdata/golint/sort.go
Fixes panic of ast_utils.FuncSignatureIs with type names of types other than ast.Ident (ast.SelectorExpression, ast.StarExpression)
The bug makes revive panic if the code under analysis has a method named Less, Len, or Swap with parameters of types represented as ast.SelectorExpression or ast.StarExpression in the AST.
> fix: ast_utils.FuncSignatureIs panics with types names other than ast.Ident

- rule/receiver_naming.go
Simplifies receiver-naming rule by replacing AST walker by an iteration over global declarations
> refactor (rule/receiver-naming): replace AST walker by iteration over declarations

- cli/main.go
- config/config.go
- formatter/friendly.go
- formatter/plain.go
- formatter/stylish.go
- formatter/unix.go
- lint/file.go
- lint/linter.go
- lint/package.go
- lint/rule.go
- logging/logger.go
This PR:
1. removes unused code
2. replaces byte buffers with string builders when possible
3. removes if-then-else chains with switch and/or reduce nesting
4. renames some local variables
> refactor: code cleanup

- go.mod
- go.sum
- lint/failure.go
- lint/file.go
- lint/linter.go
- lint/package.go
- rule/add_constant.go
This is PR adds the necessary modifications in the linting machinery to allow removing panics from rules.
It leverages the failure mechanism to communicate errors thus no need to change the rules interface.
It has the nice property of not requiring all rules to be modified at once.
> refactor: modifies linting machinery to use Failure as a mean to signal erros in rules application

- rule/string_format.go
This PR removes `#region`/`#endregion` comments as they are not a Go standard. Additionally, they are only added for one rule.
> chore: remove unused #region comments

- cli/main.go
- config/config.go
- lint/filefilter.go
- lint/linter.go
- revivelib/core_test.go
- rule/bare_return.go
- rule/context_as_argument.go
- rule/error_strings.go
- rule/filename_format.go
- rule/modifies_value_receiver.go
- rule/unreachable_code.go
- rule/var_naming.go
- test/utils_test.go
- **refactor: fix thelper issues**
- **refactor: fix govet issues**
- **refactor: fix gosimple issue**
- **refactor: fix errorlint issues**
- **refactor: fix revive issue about comment spacing**
- **refactor: fix revive issue about unused-receiver**
- **refactor: fix revive issues about unused-parameter**
- **refactor: fix gocritic issues about commentedOutCode**
> refactor: fix linting issues

- internal/ifelse/doc.go
- rule/bare_return.go
- rule/early_return.go
- rule/indent_error_flow.go
- rule/superfluous_else.go
> chore: use US English instead of UK English

- rule/enforce_repeated_arg_type_style.go
- rule/struct_tag.go
The PR refactors code for `enforce-repeated-arg-type-style` and `struct-tag` rules
> refactor: simplify by using `switch` instead of `if`

- .goreleaser.yml
This PR updates the GoReleaser configuration to v2.
Fixes #1104
> chore: migrate goreleaser config to v2

- config/config.go
- config/config_test.go
The PR adds tests for the `config.GetFormatter` and simplifies it.
> refactor: simplify config.GetFormatter; add tests

- formatter/friendly.go
- formatter/friendly_test.go
This PR replaces `sort.Slice` with `slices.SortFunc` in `Friendly.printStatistics`. See https://go-review.googlesource.com/c/go/+/626038 for reasons.
The PR adds `TestFriendly_printStatistics` to check that sorting works as expected, as it was not covered by any test before.
> refactor: use slices.SortFunc instead of sort.Slice

- cli/main.go
- cli/main_test.go
- go.mod
- go.sum
This PR replaces the archived `github.com/mitchellh/go-homedir` package dependency with `os`.
The repository https://github.com/mitchellh/go-homedir has been archived by the owner on Jul 22, 2024. For our needs, `homedir.Dir` can be replaced with `os.UserHomeDir` since Go 1.20. See mitchellh/go-homedir#34 for more details.
> refactor: get rid of mitchellh/go-homedir package

- README.md
The PR updates "Text Editors" in README:
- Remove `Atom` from docs as it is not supported any more https://github.blog/news-insights/product-news/sunsetting-atom/
- Update VSCode with info about `go.lintTool` setting.
> docs: update "Text Editors" section

- go.sum
This PR cleans up `go.sum` after this PR merged: https://github.com/mgechev/revive/pull/1200
The problem is that @renovate-bot won't run `go mod tidy` unless configured so.
> [chore] clean up go.sum

- lint/config.go
- lint/file.go
- revive.toml
The PR enables `use-any` rule in the project's revive config and replaces `interface{}` with `any`.
> refactor: fix 'use-any' revive issues

- .github/workflows/lint.yaml
- rule/string_format.go
Without providing the `path`, revive doesn't analyze all files. The resulting command is:
```sh
revive -formatter ndjson -config revive.toml
```
It looks like there's a bug in morphy2k/revive-action#156.
Now, we have a warning in the codebase:
Which I fixed in the second commit.
> fix: running revive in CI

- rule/exported.go
- test/exported_test.go
- testdata/exported_issue_1202.go
They were invalid but not reported with the correct message.
So they were wrongly caught by golangci-lint that excluded them by default.
Fixes #1202
> fix: invalid message reported for directive comment

- rule/flag_param.go
- testdata/flag_param.go
> fix: flag-parameter rule wrongly detects var definition 

- rule/unconditional_recursion.go
- testdata/unconditional_recursion.go
The root cause of the bug was that the analyzer  (AST walker) was not reinitialized at the end of function bodies. Thus, if the function was called outside the body (like in the example below) the analyzer raised a failure.
```go
func foo() int {
return 0
}
var f = foo()
```
The fix is: iterate over global declarations of the file and create an analyzer for each function declaration (instead of create a single analyzer for the whole file) Like that, each analyzer is scoped within a single function body.
Closes #1212
> fix: unconditional-recursion false positive when the function is called right after its declaration (#1212)

- .github/workflows/lint.yaml
This PR extends GitHub Actions:
- Check if there is any dirty change for `go mod tidy`.
- Check if `gofmt` produced any changes.
Avoid situations like https://github.com/mgechev/revive/pull/1060#discussion_r1934230894 and https://github.com/mgechev/revive/pull/1060#discussion_r1934234389
`Check go mod` Copied from https://github.com/golangci/golangci-lint/blob/87da074ca5995c356532643f2713fd0175702711/.github/workflows/pr.yml#L16-L28
> chore: check go.mod and gofmt in CI

- internal/astutils/ast_utils.go
- testdata/golint/sort.go
> fix: panic with getFieldTypeName

- lint/package.go
- rule/struct_tag.go
- test/struct_tag_test.go
- testdata/go1.24/go.mod
- testdata/go1.24/struct_tag.go
Go 1.24 introduces `omitzero` struct tag for JSON. This PR modifies `struct-tag` rule to support `omitzero` in code bases compiling in Go 1.24 or higher.
> feature: add support for omitzero in rule struct-tag

- rule/struct_tag.go
- test/struct_tag_test.go
- testdata/struct_tag.go
- testdata/struct_tag_user_options.go
This PR extends struct-tag rule to check URL tags as defined at https://github.com/google/go-querystring (cf https://go.dev/wiki/Well-known-struct-tags#list-of-well-known-struct-tags)
> feature: add support for URL struct tags in struct-tag rule

- rule/struct_tag.go
- test/struct_tag_test.go
- testdata/struct_tag.go
- testdata/struct_tag_user_options.go
This PR extends struct-tag rule to check datastore tags as defined at https://pkg.go.dev/cloud.google.com/go/datastore (cf https://go.dev/wiki/Well-known-struct-tags#list-of-well-known-struct-tags)
> feature: add support of datastore struct tags in struct-tag rule

- rule/struct_tag.go
- test/struct_tag_test.go
- testdata/struct_tag.go
- testdata/struct_tag_user_options.go
This PR extends struct-tag rule to check mapstructure tags as defined at https://pkg.go.dev/github.com/mitchellh/mapstructure (cf https://go.dev/wiki/Well-known-struct-tags#list-of-well-known-struct-tags)
> feature: add suport of mapstructure struct tags in struct-tag rule

- rule/struct_tag.go
- test/struct_tag_test.go
- testdata/struct_tag.go
- testdata/struct_tag_user_options.go
This PR extends struct-tag rule to check validate tags as defined at https://github.com/go-playground/validator (cf https://go.dev/wiki/Well-known-struct-tags#list-of-well-known-struct-tags)
> feature: add suport of validate struct tags in struct-tag rule

- RULES_DESCRIPTIONS.md
This PR extends the `error-strings` rule description. `error-strings` has a configuration since v1.2.2 that was added in #703.
> docs: describe configuration for `error-strings` rule

- rule/error_strings.go
- rule/error_strings_test.go
- test/error_strings_custom_functions_test.go
- testdata/error_strings_issue_1243.go
The PR fixes a bug in the `error-strings` rule where configuring custom functions overwrites default functions.
When configuring custom functions to `["errors.Wrap"]`, the internal map `r.errorFunctions` would be:
```go
r.errorFunctions = map[string]map[string]struct{}{
"fmt": {
"Errorf": {},
},
"errors": {
"Wrap": {},
},
}
```
but it should be:
```go
r.errorFunctions = map[string]map[string]struct{}{
"fmt": {
"Errorf": {},
},
"errors": {
"Errorf":       {},
"WithMessage":  {},
"Wrap":         {},
"New":          {},
"WithMessagef": {},
"Wrapf":        {},
},
}
```
Fixes #1243
> fix: error-strings custom funcs overwrites defaults

- rule/unused_param.go
- rule/unused_receiver.go
The PR changes the `Configure` function for both `UnusedReceiverRule` and `UnusedParamRule` to return an error instead of panicking. This is a leftover from #1185.
> refactor: return an error instead of panicking

- rule/struct_tag.go
- test/struct_tag_test.go
- testdata/struct_tag.go
- testdata/struct_tag_user_options.go
This PR extends struct-tag rule to check TOML tags as defined at https://pkg.go.dev/github.com/pelletier/go-toml (cf https://go.dev/wiki/Well-known-struct-tags#list-of-well-known-struct-tags)
> feature: add support for TOML struct tags in struct-tag rule

- lint/file.go
- lint/file_test.go
- lint/linter.go
This PR performs some refactoring for the function `File.disabledIntervals` and add basic tests to cover most common cases.
> refactor: simplify File.disabledIntervals, add tests

- lint/package.go
- rule/datarace.go
- rule/range_val_address.go
- rule/range_val_in_closure.go
- rule/redefines_builtin_id.go
- rule/redundant_test_main_exit.go
- rule/struct_tag.go
The PR introduces `lint.IsAtLeastGoVersion` to factor-out the common code of lint.IsAtLeastGo1*
> refactor: replace IsAtLeastGo1* functions by IsAtLeastGoVersion

- RULES_DESCRIPTIONS.md
I noticed this while opening https://github.com/golangci/golangci-lint/pull/5692
> docs: place `redundant-build-tag` before `redundant-import-alias`

- rule/useless_break.go
- testdata/useless_break.go
> fix false positive in useless-break when a label follows a break

- RULES_DESCRIPTIONS.md
- rule/struct_tag.go
- testdata/struct_tag.go
Closes #1269 
type checking default values for slices is omitted on purpose (might be added later)
A PR for cleaning up the whole rule's code will follow
> feature: add support for properties tag in struct-tag rule

- README.md
Let's sort the rules in `README.md` as we are already doing in `RULES_DESCRIPTIONS.md`.
Follows #1288
> docs: sort rules in README table

- rule/error_strings.go
- testdata/golint/error_strings.go
Closes #1264 by accepting words with more than two capital letters at the beginning of error messages
> feature: Improve error-strings rule to detect acronyms and proper nouns

- rule/struct_tag.go
- testdata/go1.24/struct_tag.go
- testdata/struct_tag.go
- testdata/struct_tag_user_options.go
This PR proposes  a ~full rewriting of the rule `struct-tag` in an attempt to clean-up the implementation.
This PR introduces the following changes:
1. Defines a common signature for tag-checker functions
2. Normalizes failure messages
3. Reduces the implementation complexity of some checks (protobuf, properties, ...)
> struct-tag: change reported messages and refactor implementation

- .github/workflows/build.yaml
- .github/workflows/lint.yaml
- .github/workflows/test.yaml
The `edited` event is related to the edition of the title or the description of a PR.
I think you don't need to re-launch the CI after an edition of a title.
> chore: remove edited trigger

- rule/unexported_return.go
**This PR needs PR #1307.**
The problem of consistency was related to a missing call to `Package.TypeCheck()`.
The `UnexportedReturnRule` calls `Package.TypeOf()`, but this requires the data from `Package.TypeCheck()`: depending on the order of the rule, the data may exist or may not.
I checked the calls to `Package.TypeOf()`, and it is only missing for `unexported-return`.
The bad news is that `unexported-return` is now a part of the [other issue](https://github.com/mgechev/revive/issues/1277) about `Package.TypeCheck()`.
Concretely, it was already a part of this issue as it relies on `Package.TypeOf()`.
The regression comes from [#1170](https://github.com/mgechev/revive/pull/1170/files) (v1.6.0); this explains why the number of issues has increased since the beginning of the year.
Note: …
> fix(unexported-return): add missing TypeCheck call

- README.md
This PR updates the "golangci-lint" section in README to the newest golangci-lint v2 configuration.
See https://golangci-lint.run/product/migration-guide/ and https://golangci-lint.run/usage/linters/#revive
> docs: update golangci-lint configuration to v2

- rule/var_naming.go
- test/utils_test.go
- testdata/golint/a_pkg_with_caps.go
- testdata/golint/another_pkg_with_caps.go
- testdata/golint/pkg_caps.go
- testdata/golint/var_naming.go
- testdata/var_naming_skip_package_name_checks_false.go
This PR is related to #1317, more specifically to 
[Generate a single failure per package (instead of one for each file in a package)]( https://github.com/mgechev/revive/pull/1312#pullrequestreview-2770906632)
Here, "check" must be understood as "check package name"
Remarks:
1. The proposed implementation checks only once each package name. This is accomplished by checking source file and keeping a reference to the directory it belongs to; after, no other file in the same directory will be checked.
2. Testing required a trick. Standard test method allows checking only one file at the time thus it is inappropriate to test package-wide checks. On the other side, `var-naming` rule is tested with other `golint`-related rules. These rules are tested differently, by executing all of them in a …
> var-name checks each package name only once

- README.md
This simple change fixes displaying of the "Available Rules" table on https://revive.run/docs#available-rules
<details><summary>Before</summary>
<p>
</p>
</details> 
<details><summary>After</summary>
<p>
</p>
</details>
> docs: fix displaying rules table on revive.run

- .github/workflows/lint.yaml
- .golangci.yml
- formatter/formatter_test.go
- formatter/friendly.go
- lint/package.go
- rule/datarace.go
- rule/early_return.go
- rule/error_strings_test.go
- rule/if_return.go
- rule/import_alias_naming_test.go
- rule/import_shadowing.go
- rule/range_val_address.go
- rule/unused_param.go
Integrate [golangci-lint](https://golangci-lint.run/) into the CI/CD pipeline to ensure code quality and consistency across the project.
1. Add golangci-lint config with minimal configuration. The config could be based on https://github.com/ccoVeille/golangci-lint-config-examples
2. Extend GitHub Actions Workflow .github/workflows/lint.yaml with golangci-lint job. It should use [golangci-lint-action](https://github.com/marketplace/actions/golangci-lint).
3. Run golangci-lint locally, identify, and fix existing linting issues.
4. Disabled Revive in the golangci-lint config
**Important Notes**
- I initially attempted to follow the [basic golangci-lint config](https://github.com/ccoVeille/golangci-lint-config-examples/tree/main/02-basic), but quickly ran into 34 linting issues (errcheck: 24, …
> Integrate golangci-lint into CI/CD pipeline

- formatter/formatter_test.go
- formatter/friendly.go
- formatter/sarif.go
- formatter/stylish.go
Replace function call by var ref and move def near utilization in friendly and stylish formatters
> tiny refactoring on friendly, sarif and stylish formatters

- formatter/default.go
- formatter/formatter_test.go
- formatter/sarif.go
- revivelib/core_test.go
This pull request updates all references to the old Revive documentation and site URLs, replacing them with the new `https://revive.run` domain. The changes ensure consistency across the codebase and tests by using the updated URL format.
Closes #1356
> Update rule description URLs to point to revive.run

- README.md
- RULES_DESCRIPTIONS.md
- config/config.go
- rule/time_date.go
- test/time_date_test.go
- testdata/time_date_decimal_literal.go
This commit introduces a new rule to check for the usage of [`time.Date`](https://pkg.go.dev/time#Date)
The rule is added to report the usage of `time.Date` with non-decimal literals
Here the leading zeros that seem OK, forces the value to be octal literals.
```go
time.Date(2023, 01, 02, 03, 04, 05, 06, time.UTC)
```
gofumpt formats the code like this when it encounters leading zeroes.
```go
time.Date(2023, 0o1, 0o2, 0o3, 0o4, 0o5, 0o6, time.UTC)
```
The rule also reports anything that is not a decimal literal. Please take a look at the testdata file.
Closes #1326
> time-date: add rule to check for time.Date usage

- cli/main.go
- formatter/checkstyle.go
- formatter/friendly.go
- formatter/stylish.go
- lint/failure.go
- revivelib/core.go
- revivelib/pattern.go
This PR removes the prefix `get` from getter methods (see [Getters](https://go.dev/doc/effective_go#Getters))
Note: this PR includes modifications in 3 functions from `main` that are not strictly getters but removing the `get` prefix makes them read better.
> refactor: removes `get` from getters names

- test/golint_test.go
- test/utils_test.go
Avoids parsing instructions twice and simplifies signature of asserting functions
1. Original code parsed test instructions twice:
```golang
if parseInstructions(t, fullFilePath, src) == nil {   // first parsing
assertSuccess(t, baseDir, stat, []lint.Rule{rule}, c)
return
}
assertFailures(t, baseDir, stat, src, []lint.Rule{rule}, c) // second parsing inside assertFailures
```
2. Functions `assertSuccess` and `assertFailures` both took `baseDir string, fi os.FileInfo` as arguments to do exactly the same file path reconstruction that callers already do. Simplified both to receive the file path.
> refactor: test utils functions by removing redundant test instructions parsing and simplifying asserting functions

- .github/workflows/lint.yaml
- DEVELOPING.md
- README.md
- RULES_DESCRIPTIONS.md
- mdsf.json
The PR fixes the formatting of code blocks in all Markdown files.md. It also adds [`mdsf`](https://mdsf.mhouge.dk/) to lint formatting in CI.
The following formatters were chosen:
- [goimports](https://pkg.go.dev/golang.org/x/tools/cmd/goimports) for `go`
- [shfmt](https://github.com/mvdan/sh) for `sh`, `bash`, `shell`
- [taplo](https://taplo.tamasfe.dev/cli/introduction.html) for `toml`
Some Go code snippets can't be formatted with `goimports`. I marked them with `golang` - this way, GitHub displays them as Go code, but `mdsf` will skip them. The similar for `shellsession` - `shfmt` can't format it, so I disabled.
Updates #1350
> docs: format code snippets in markdown files

- README.md
- RULES_DESCRIPTIONS.md
- config/config.go
- internal/astutils/ast_utils.go
- rule/unnecessary_format.go
- test/unnecessary_format_test.go
- testdata/unnecessary_format.go
The rule spots calls to formatting functions without leveraging formatting directives.
Like:
```golang
log.Printf("UDP server exited") // can be replaced with log.Print
fmt.Fprintf(writer, " }") //  fmt.Fprint
message := fmt.Sprintf("contains an invalid SecurityDefinitionsItem") // fmt.Sprint or just "contains an invalid SecurityDefinitionsItem"
```
The implementation doesn't try to be smart to cope with corner cases, it just checks if the _format_ argument of the functions contains `%`. It also avoids relying on type information and limits itself to check some common patterns (like calling `t` the variable holding `*testing.T` or `logger` the variable holding a standard logger instance)
[In the future someone will ask for adding a configuration to define their own functions to check; and …
> new rule to spot unnecessary use of formatting functions

- .golangci.yml
- cli/main.go
- cli/main_test.go
- lint/file.go
- lint/filefilter.go
- lint/name.go
- lint/package.go
- revivelib/core.go
- rule/dot_imports.go
- rule/import_alias_naming.go
- rule/import_alias_naming_test.go
- rule/imports_blocklist.go
- rule/redundant_import_alias.go
- rule/string_format.go
- rule/struct_tag.go
- rule/var_naming.go
- test/utils_test.go
This PR enables [`gocritic`](https://golangci-lint.run/usage/linters/#gocritic) linter and fixes up its issues.
I decided to enable [all gocritic checks](https://go-critic.com/overview.html) except the performance ones: [`hugeParam`](https://go-critic.com/overview.html#hugeparam) and [`rangeValCopy`](https://go-critic.com/overview.html#rangevalcopy).
> [!NOTE]
> `sync.RWMutex` in the `lint.Package` is now unexported. This break a code that relies on `lint.Package.RLock, lint.Package.RUnlock, lint.Package.Lock, lint.Package.Unlock`. But it's unlikely someone uses these methods directly.
<details><summary>All fixed issues</summary>
<p>
```console
$ golangci-lint run
cli/main.go:193:7: emptyStringTest: replace `len(buildInfo) == 0` with `buildInfo == ""` (gocritic)
if len(buildInfo) == 0 {
^ …
```
> refactor: enable gocritic linter; fix lint issues

- .golangci.yml
- cli/main_test.go
It allows us to report errors at the right place in the tests.
There was only one function that was not using the helper.
It has been fixed to use it.
> chore: enable thelper linter in golangci-lint

- .golangci.yml
There is no errors right now, but it could avoid future issues.
> chore: enable dupword linter in golangci-lint

- RULES_DESCRIPTIONS.md
- rule/time_date.go
- test/time_date_test.go
- testdata/time_date_decimal_literal.go
- testdata/time_date_out_of_bounds.go
dates are checked with the following rules:
- no validation for year
- month must be between 1 and 12
- day must be between 1 and 31 for January, March, May, July, August, October, December
- day must be between 1 and 30 for April, June, September, November
- day must be between 1 and 28 for February, or 29 for leap years
- hour must be between 0 and 23
- minute must be between 0 and 59
- second must be between 0 and 59 (and 60 for leap seconds)
- nanosecond must be between 0 and 999999999, because otherwise you can use a second
Fixes #1369 
- #1369
> feature: detect time/date out of bounds in time-date rule

- lint/file.go
- rule/unexported_return.go
- test/unexported_return_test.go
- testdata/unexported_return_package_foo.go
- testdata/unexported_return_package_foo_test.go
- testdata/unexported_return_package_footest_test.go
- testdata/unexported_return_package_main.go
- testdata/unexported_return_package_main_test.go
- testdata/unexported_return_package_maintest_test.go
The content of these files cannot be imported by other packages,
so they are excluded from the `unexported_return` rule.
Related to https://github.com/mgechev/revive/issues/1397#issuecomment-2943897721
> unexported_return: exclude main package and test files

- rule/var_naming.go
- rule/var_naming_test.go
- test/var_naming_test.go
```toml
[rule.var-naming]
arguments = [[], [], [{ extra-bad-package-names = ["helpers", "models"] }]]
```
```console
$ revive --version
version 1.10.0
$ revive ./...                                               
initializing revive - getting lint rules: cannot configure rule: "var-naming": invalid third argument to the var-naming rule. Expecting extraBadPackageNames of type slice of strings, but []interface {}
```
With my PR:
```console
$ ./revive ./...    
helpers/helpers.go:1:9: avoid bad package names
```
Related to #1312
> fix: var-naming rule extraBadPackageNames type

- rule/var_naming.go
- rule/var_naming_test.go
This PR fixes a panic when running revive with the following configuration:
```toml
[rule.var-naming]
arguments = [[], [], [{ extra-bad-package-names = ["helpers", 123] }]]
```
Before:
```console
❯ ./revive -config revive.toml ./...
panic: interface conversion: interface {} is int64, not string
goroutine 1 [running]:
github.com/mgechev/revive/rule.(*VarNamingRule).Configure(0x1053e2ec0, {0x140001d37d0, 0x3, 0xa?})
/Users/alexandear/src/github.com/mgechev/revive/rule/var_naming.go:94 +0x554
github.com/mgechev/revive/config.GetLintingRules(0x140001cdab0, {0x10540a7e0, 0x0, 0x8?})
/Users/alexandear/src/github.com/mgechev/revive/config/config.go:158 +0x3c8
github.com/mgechev/revive/revivelib.New(0x140001cdab0, 0x0, 0x0, {0x0, 0x0, 0x140000021c0?}) …
```
> var-naming: handle possible panic

- .github/workflows/lint.yaml
- .golangci.yml
- Makefile
- cli/main.go
- formatter/friendly.go
- formatter/sarif.go
- formatter/stylish.go
- revivelib/core.go
- revivelib/core_test.go
- rule/cognitive_complexity.go
- rule/struct_tag.go
- test/redundant_import_alias_test.go
This PR enables `gofmt`, `gci`, and `goimports` formatters in golangci-lint config.
Additionally, the PR removes `gofmt` job from the GitHub Actions workflow, since formatting is now handled by `golangci-lint`.
> chore: enable formatters in golangci-lint config

- README.md
This PR adds a link to `https://deepwiki.com/mgechev/revive` to README, so everyone can understand better the architecture of Revive.
DeepWiki provides up-to-date documentation you can talk to, for every repo in the world. Think Deep Research for GitHub.
> docs: add DeepWiki link to README

- rule/exported.go
- test/exported_test.go
- testdata/exported_issue_1235.go
This PR improves the error reporting of exported rules
The idea was developed in #1235, we want to provide more information such as:
- the case changed
- the variable is now exported
Explore:
- #1226 
- #1235
> exported: improve error message

- internal/astutils/ast_utils.go
- internal/ifelse/branch_kind.go
- rule/identical_branches.go
- rule/struct_tag.go
- testdata/identical_branches.go
This PR extends `identical-branches` rule to analyse `switch` statements.
Notes:
1. Only un-tagged switches are not analysed because the order of case evaluation might be important thus two identical branches might exist but can not be merged into one case.
2. Branches ending with a `fallthrough` are not taken into account because the semantics of such branches is defined by the subsequent branch.
3. There are a lot of identical switch branches out there. For example, running the rule against Kubernetes code-base results in ~290 failures. Most of these failures do not spot actual logic problems in the code but more a "style" problem.
Closes #1442
> feature: detect identical-branches in switch statements

- README.md
- RULES_DESCRIPTIONS.md
- config/config.go
- rule/identical_ifelseif_condition.go
- test/identical_ifelseif_conditions_test.go
- testdata/identical_ifelseif_conditions.go
This PR adds `identical-ifelseif-conditions`, a new rule to warn on if...else if chains with repeated conditions.
Closes #1444
> feature: new rule identical-ifelseif-conditions

- rule/datarace.go
Micro PR that declares the deprecated `*ast.Object` into a private type to "encapsulate" the deprecated type.
> refactor: reduces the number of references to deprecated *ast.Object

- RULES_DESCRIPTIONS.md
- rule/struct_tag.go
- test/struct_tag_test.go
- testdata/struct_tag.go
- testdata/struct_tag_user_options.go
Adds support for Google Cloud Spanner struct tags to the `struct-tag` rule.
- Added `keySpanner` constant for the spanner tag key
- Implemented `checkSpannerTag` function with validation for:
- Special case `spanner:"-"` (ignore field during decoding)
- Regular field name mappings like `spanner:"column_name"`
- User-defined options through configuration
- Added spanner to tag name checking logic
- Added spanner to the tagCheckers map
The implementation follows the same pattern as existing tag checkers (JSON, XML, YAML, etc.) and handles the documented spanner tag behavior from the official Go client library.
Closes #1475
> struct-tag: support spanner struct tag

- formatter/default.go
The default formatter generates an extra empty line at the end of the failure list
This PR removes the artifact.
> fix: default formatter generates an extra new line

- rule/struct_tag.go
- testdata/go1.24/struct_tag.go
- testdata/struct_tag.go
- testdata/struct_tag_user_options.go
This PR completes #1483 by detecting useless options on other known struct tags.
For some tags, using `-` to indicate "ignore field" is not formally defined nor documented but open source code bases use it.
> feature: struct-tag warns on (useless) options on ignored fields

- rule/struct_tag.go
- testdata/struct_tag.go
Closes #1524 by adding `omitempty` to the list of accepted options for `validate`
> fix: rule `struct-tag` false positive on `validate:omitempty`

- rule/defer.go
- testdata/defer.go
Closes #1528 by using a counter to keep track of the function literal nesting level and reporting a failure only if the return is at the first level.
> fix: false positive for `return in a defer function has no effect`

- rule/confusing_naming.go
- testdata/confusing_naming1.go
The `confusing-naming` rule was incorrectly reporting false positives when Go structs contained multiple blank identifier (`_`) fields, which are commonly used for padding and alignment. The rule's `checkStructFields` function was treating all field names equally, including blank identifiers, causing it to flag the second occurrence of `_` as differing only by capitalization from the first. This fix adds a simple check to skip blank identifiers before performing the capitalization comparison, as blank identifiers are special in Go and explicitly allowed to appear multiple times in the same struct according to the language specification.
Example:
```go
// test.go
package main
type siginfoChild struct {
signo    int32
errno    int32
exitCode int32
_        int32
pid    int32
uid    uint32 …
```
> fix: rule `confusing-naming` false positive on multiple blank identifiers
